// src/components/SourceBadge.vue
<script lang="tsx">
import Vue from "vue";
import Component from "vue-class-component";
import { Prop } from "vue-property-decorator";

import { CurrentEvent, CurrentDate } from "@/libs/Const";
import { UnitData } from "@/libs/DB";
import EntitySource from "@/libs/EntitySource";

@Component({})
export default class SourceBadge extends Vue {
	@Prop({
		type: [String, Object],
		required: true,
	})
	private source!: string | EntitySource;

	@Prop({
		type: Boolean,
		default: false,
	})
	private detail!: boolean;

	@Prop({
		type: Boolean,
		default: false,
	})
	private minimum!: boolean;

	@Prop({
		type: Boolean,
		default: false,
	})
	private linked!: boolean;

	private get Source () {
		return typeof this.source === "string"
			? new EntitySource(this.source)
			: this.source;
	}

	private Link (e: Event, link: string) {
		e.preventDefault();
		this.$router.push({ path: link });
	}

	private render () {
		const variant = (() => {
			if (this.Source.IsUninstalled) return this.minimum ? "black" : "light";
			if (this.Source.IsChallenge) return "primary";
			if (this.Source.IsPrivateItem) return "stat-acc";
			if (this.Source.IsLimited) return "secondary";
			if (this.Source.IsEndlessWar) return this.minimum ? "light" : "dark";
			if (this.Source.IsSideMap) return "success";
			if (this.Source.IsExMap) return "danger";
			if (this.Source.IsMap) return "warning";
			if (this.Source.IsApocrypha) return "apocrypha";
			if (this.Source.IsExchange) {
				return this.Source.IsEvent
					? this.Source.EventId === CurrentEvent
						? "event-exchange"
						: "event-exchange-old"
					: this.Source.ExchangeDate === CurrentDate
						? "exchange"
						: "exchange-old";
			}
			return "info";
		})();

		const content = (() => {
			if (this.Source.IsUninstalled)
				return "미구현";
			else if (this.Source.IsPrivateItem) {
				const unit = UnitData[this.Source.PrivateId];
				return `${unit.name}`;
			} else if (this.Source.IsLimited)
				return "획득처 없음";
			else if (this.Source.IsChallenge) {
				const text = this.Source.IsReward ? "최종 보상" : "클리어 보상";

				if (this.detail)
					return `외부 통신 요청 (${this.Source.ChallengeName}, ${this.Source.ChallengeDifficulty}) ${text}`.trim();
				else
					return "외부 통신 요청";
			} else if (this.Source.IsEndlessWar) {
				if (this.detail)
					return `영원한 전장 (${this.Source.EndlessWarPrice} 광물)`;
				else
					return "영원한 전장";
			} else if (this.Source.IsApocrypha) {
				if (this.detail) {
					if (this.Source.ApocryphaNumber)
						return `${UnitData[this.Source.ApocryphaUnit].name} 외전 ${this.Source.ApocryphaNumber}부`;
					else
						return `${UnitData[this.Source.ApocryphaUnit].name} 외전`;
				} else
					return "외전";
			} else if (this.Source.IsExchange) {
				if (this.Source.IsEvent) {
					const event = this.Source.FullEventName;
					const data = this.Source.ExchangePrice || { item: "?", value: 0 };
					const item = this.Source.ExchangeItemName;

					if (this.detail) {
						return [
							event,
							` '${item}' `/* 아이템 아이콘 컴포넌트 */,
							`${data.value}개`,
						];
					} else if (this.minimum)
						return "이벤트 교환소";
					else
						return event;
				} else {
					const data = this.Source.MonthlyData || { year: "?", month: "?" };
					if (this.detail)
						return `${data.year}년 ${data.month}월 교환소`;
					else
						return "교환소";
				}
			} else {
				const text = this.Source.IsReward ? "클리어 보상" : "";
				if (this.Source.IsEvent) {
					const event = this.Source.FullEventName;

					if (this.detail)
						return `${event} ${this.Source.Map} ${text}`.trim();
					else if (this.minimum)
						return "이벤트";
					else
						return event;
				} else {
					if (this.detail)
						return `${this.Source.Map} ${text}`.trim();
					else
						return `${this.Source.Map}`;
				}
			}
		})();

		if ((typeof content === "string" && content) || (content.length > 0)) {
			if (this.linked && this.Source.IsMap) {
				const area = ((x) => {
					if (!x.includes("-")) return x;

					let ls = x.substr(0, x.indexOf("-"));
					if (!ls.startsWith("Ev")) return ls;
					ls = ls.substr(2);

					if (!ls) return 1;
					return ls;
				})(this.Source.Map);
				const link = `/worlds/${this.Source.EventId}/${area}/${this.Source.Map}`;

				return <a href={link} onClick={(e: Event) => this.Link(e, link)}>
					<b-badge class="source-badge mx-1" variant={variant} data-source={this.Source.toString()}>{content} 🔗</b-badge>
				</a>;
			} else
				return <b-badge class="source-badge mx-1" variant={variant} data-source={this.Source.toString()}>{content}</b-badge>;
		} else
			return <i />;
	}
}
</script>

// src/components/source-badge/index.tsx
import { Fragment, FunctionalComponent, h } from "preact";
import { Link, route } from "preact-router";

import { FilterableUnit } from "@/types/DB/Unit.Filterable";

import { CurrentEvent, CurrentDate } from "@/libs/Const";
import EntitySource from "@/libs/EntitySource";

import Loader, { StaticDB, GetJson } from "@/components/loader";
import Locale, { LocaleExists } from "@/components/locale";
import Icon from "@/components/bootstrap-icon";

interface SourceBadgeProps {
	class?: string;
	source: EntitySource | string;
	minimum?: boolean;
	detail?: boolean;
	linked?: boolean;
}

const SourceBadge: FunctionalComponent<SourceBadgeProps> = (props) => {
	const Source = typeof props.source === "string"
		? new EntitySource(props.source)
		: props.source;

	const variant = ((): string => {
		if (Source.IsUninstalled) return props.minimum ? "black" : "light text-dark";
		if (Source.IsRoguelike) return "warning text-dark";
		if (Source.IsChallenge) return "primary";
		if (Source.IsPrivateItem) return "stat-acc text-dark";
		if (Source.IsLimited) return "secondary";
		if (Source.IsEndlessWar) return props.minimum ? "light text-dark" : "dark";
		if (Source.IsSideMap) return "success";
		if (Source.IsExMap) return "danger";
		if (Source.IsMap) return "warning text-dark";
		if (Source.IsSubStory) return "substory";
		if (Source.IsExchange) {
			return Source.IsEvent
				? Source.EventId === CurrentEvent
					? "event-exchange"
					: "event-exchange-old"
				: Source.ExchangeDate === CurrentDate
					? "exchange"
					: "exchange-old";
		}
		return "info";
	})();

	return <Loader json={ StaticDB.FilterableUnit } content={ ((): preact.VNode => {
		const FilterableUnitDB = GetJson<FilterableUnit[]>(StaticDB.FilterableUnit);

		const content = ((): preact.VNode => {
			if (Source.IsUninstalled)
				return <Locale k="COMMON_SOURCE_NOT_IMPLEMENTED" />;
			else if (Source.IsRoguelike)
				return <Locale k="COMMON_SOURCE_ROGUELIKE" />;
			else if (Source.IsPrivateItem) {
				const unit = FilterableUnitDB.find(x => x.uid === Source.PrivateId);
				if (unit) return <Locale k={ `UNIT_${unit.uid}` } />;
				return <Fragment>{ Source.PrivateId }</Fragment>;
			} else if (Source.IsLimited)
				return <Locale k="COMMON_SOURCE_LIMITED" />;
			else if (Source.IsChallenge) {
				const key = `COMMON_CHALLENGE_${Source.ChallengeId}`;
				const name = LocaleExists(key)
					? <Locale k={ `COMMON_CHALLENGE_${Source.ChallengeId}` } />
					: <Fragment>{ Source.ChallengeId }</Fragment>;

				const text = Source.IsReward
					? <Locale k="COMMON_SOURCE_FINISH_REWARD" />
					: <Locale k="COMMON_SOURCE_CLEAR_REWARD" />;
				// const ChallengeName: Record<string, string> = {
				// 	1: "밀고, 당기고, 불질러!",
				// 	2: "피조물과 설계자",
				// 	3: "실패작의 폭주",
				// 	4: "레모네이드 VR",
				// 	5: "바다의 소녀들",
				// };

				if (props.minimum)
					return <Locale k="COMMON_SOURCE_CHALLENGE" />;
				else if (props.detail) {
					return <Fragment>{
						[
							<Locale k="COMMON_SOURCE_CHALLENGE" />,
							<Fragment>({ name }&nbsp;{ Source.ChallengeDifficulty })</Fragment>,
							text,
						].filter(x => x).gap(<Fragment>&nbsp;</Fragment>)
					}</Fragment>;
				}
				return <Fragment>{
					[name, Source.ChallengeDifficulty]
						.filter(x => x)
						.gap(<Fragment>&nbsp;</Fragment>)
				}</Fragment>;
			} else if (Source.IsEndlessWar) {
				if (props.detail)
					return <Locale k="COMMON_SOURCE_EW_RESOURCES" p={ [Source.EndlessWarPrice] } />;
				return <Locale k="COMMON_SOURCE_EW" />;
			} else if (Source.IsSubStory) {
				const text = Source.IsReward
					? <Locale k="COMMON_SOURCE_CLEAR_REWARD" />
					: <Fragment />;
				if (!props.minimum) {
					return <Fragment>
						<Locale
							k="COMMON_SOURCE_SUBSTORY"
							p={ [<Locale k={ `UNIT_${Source.SubStoryUnit}` } fallback={ Source.Map } />] }
						/>
							 &nbsp;{ text }
					</Fragment>;
				}
				return <Locale k="COMMON_SOURCE_SUBSTORY_SINGLE" />;
			} else if (Source.IsExchange) {
				if (Source.IsEvent) {
					const event = Source.FullEventName;
					const data = Source.ExchangePrice || { item: "?", value: 0 };
					const item = Source.ExchangeItemName;

					if (props.detail) {
						return <Fragment>{
							[
								<Locale k={ event } />,
								`'${item}'`, // 아이템 아이콘 컴포넌트
								<Locale k="COMMON_SOURCE_EXCHANGE_COUNT" p={ [data.value] } />,
							].filter(x => x).gap(<Fragment>&nbsp;</Fragment>)
						}</Fragment>;
					} else if (props.minimum)
						return <Locale k="COMMON_SOURCE_EXCHANGE_EVENT" />;
					return <Fragment>
						{ event }&nbsp;
						<Locale k="COMMON_SOURCE_EXCHANGE" />
					</Fragment>;
				}
				const data = Source.MonthlyData || { year: "?", month: "?" };
				if (!props.minimum)
					return <Locale k="COMMON_SOURCE_EXCHANGE_DATE" p={ [data.year, data.month] } />;
				return <Locale k="COMMON_SOURCE_EXCHANGE" />;
			}
			const text = Source.IsReward
				? <Locale k="COMMON_SOURCE_CLEAR_REWARD" />
				: <Fragment />;

			if (Source.IsEvent) {
				const event = Source.FullEventName;

				if (props.detail) {
					return <Fragment>{
						[
							<Locale k={ event } />,
							Source.Map,
							text,
						]
							.filter(x => x)
							.gap("&nbsp;")
					}</Fragment>;
				}
				// else if (minimum && Source.IsExMap)
				// 	return "이벤트 Ex";
				// else if (minimum && Source.IsSideMap)
				// 	return "이벤트 B";
				else if (props.minimum)
					return <Locale k="COMMON_SOURCE_EVENT" />;

				return <Fragment>{
					[
						Source.Map,
						text,
					].filter(x => x).gap(<Fragment>&nbsp;</Fragment>)
				}</Fragment>;
			}
			return <Fragment>{
				(!props.minimum ? [Source.Map, text] : [Source.Map])
					.filter(x => x)
					.gap(<Fragment>&nbsp;</Fragment>)
			}</Fragment>;
		})();

		if (props.linked && (Source.IsMap || Source.IsChallenge || Source.IsSubStory)) {
			const link = Source.IsChallenge
				? `/worlds/Cha/${Source.ChallengeId}/${Source.Map}`
				: Source.IsSubStory
					? `/worlds/Sub/1/${Source.Map}`
					: `/worlds/${Source.EventId}/${((x): string => {
						if (!x.includes("-")) return x;

						let ls = x.substr(0, x.indexOf("-"));
						if (!ls.startsWith("Ev")) return ls;
						ls = ls.substr(2);

						if (!ls) return "1";
						return ls;
					})(Source.Map)}/${Source.Map}`;

			return <Link href={ link }>
				<span
					class={ `badge bg-${variant} source-badge mx-1 ${props.class || ""}` }
					data-source={ Source.toString() }
				>
					{ content }
					<Icon icon="link-45deg" class="ms-1" />
				</span>
			</Link>;
		}
		return <span
			class={ `badge bg-${variant} source-badge mx-1 ${props.class || ""}` }
			data-source={ Source.toString() }
		>{ content }</span>;
	}) } />;
};
export default SourceBadge;
