// src/routes/units/components/unit-dialogue/index.tsx
import { Fragment, FunctionalComponent, h } from "preact";

import { RawUnitDialogueEntity, UnitDialogueDataType } from "@/types/DB/Dialogue";
import { Unit, UnitSkin } from "@/types/DB/Unit";

import { UniqueID } from "@/libs/Functions";

import Locale from "@/components/locale";
import DialogueRow from "@/routes/units/components/dialogue-row";

export interface VoiceItem extends UnitSkin {
	id: number;
	isDef: boolean;
	isPro: boolean;
	isMarriage: boolean;
}

interface UnitDialogueProps {
	unit: Unit;
	voice: VoiceItem;
	id: number;
	lang: keyof UnitDialogueDataType;

}

const UnitDialogue: FunctionalComponent<UnitDialogueProps> = (props) => {
	const unit = props.unit;
	const voice = props.voice;

	const VoiceKey = ((v): string => {
		if (v.isMarriage) return "M";
		if (v.isPro) return "P";
		if (v.isDef) return "0";
		return v.id.toString();
	})(voice);

	const TypeList = ((): Array<keyof RawUnitDialogueEntity> => {
		const db = unit.dialogue[props.lang];
		if (!db) return [];

		if (VoiceKey in db) {
			const diag = db[VoiceKey];
			return Object.keys(diag) as Array<keyof RawUnitDialogueEntity>;
		}

		return [
			...(voice.isDef && !voice.isMarriage ? ["Join"] : []),
			"SquadJoin",
			"Leader",

			"SortiePick",
			"StageStart",
			"Retreat",
			"SearchStart",
			"SearchEnd",

			"BattleFocus",
			"ActionApprove",
			"SpSkill",
			"SpSkill_1",
			"SpSkill_2",
			"SpSkill_3",
			"SpSkill_4",
			"SpSkill_5",
			"SpSkill_6",
			"SpSkill_7",
			"SpSkill_8",
			"SpSkill_9",
			"Retire",
			"Repair",
			"Reinforce",
			"ItemEquip",
			"CoreLink",
			"PresentGet",

			"Login",
			"Idle_01_01",
			"Idle_01_02",
			"Idle_01_03",
			"SPIdle_01_01",
			"Idle_02_01",
			"Idle_03_01",
			"Idle_04_01",
			"SPIdle_02_01",

			"Oath",
			"OathIdle_01",
			"MVP",
		] as Array<keyof RawUnitDialogueEntity>;
	})();

	const Dialogue = ((): Partial<RawUnitDialogueEntity> => {
		const db = unit.dialogue[props.lang];
		if (db && VoiceKey in db) return db[VoiceKey];

		/* eslint-disable camelcase */
		return {
			Join: "???",
			SquadJoin: "???",
			Leader: "???",
			SortiePick: "???",
			StageStart: "???",
			Retreat: "???",
			SearchStart: "???",
			SearchEnd: "???",
			BattleFocus: "???",
			ActionApprove: "???",
			SpSkill: "???",
			SpSkill_2: "???",
			SpSkill_3: "???",
			SpSkill_4: "???",
			SpSkill_5: "???",
			Retire: "???",
			Repair: "???",
			Reinforce: "???",
			ItemEquip: "???",
			CoreLink: "???",
			PresentGet: "???",
			Login: "???",
			Idle_01_01: "???",
			Idle_01_02: "???",
			Idle_01_03: "???",
			SPIdle_01_01: "???",
			Idle_02_01: "???",
			Idle_03_01: "???",
			Idle_04_01: "???",
			SPIdle_02_01: "???",
			Oath: "???",
			OathIdle_01: "???",
			MVP: "???",
		};
		/* eslint-enable camelcase */
	})();

	const IsVoiceAvailable = voice.V;

	const IsMissing = ((): boolean => {
		const db = unit.dialogue[props.lang];
		if (!db) return true;
		return Object.values(Dialogue).every(x => !x);
	})();

	const IsPartial = ((): boolean => {
		const db = unit.dialogue[props.lang];
		if (!db) return false;
		return Object.values(Dialogue).some(x => !x);
	})();

	const unitId = ((): string => {
		const uid = unit.uid || "";
		const postfix = ((): string => {
			if (voice.isMarriage) return "_Marriage";
			if (voice.isDef) return "";
			if (voice.isPro) return "_PS1";
			return `_NS${props.id}`;
		})();
		return `${uid}${postfix}`;
	})();

	const collapseId = UniqueID("unit-dialogue-");

	return IsVoiceAvailable
		? <div class="card mt-2 text-start" lang={ props.lang }>
			<div
				class="card-header"
				data-bs-toggle="collapse"
				data-bs-target={ `#${collapseId}` }
				aria-expanded="false"
				aria-controls={ collapseId }
				role="button"
			>
				{ props.voice.sid === null
					? <Locale k={ `UNIT_${unit.uid}` } />
					: <Locale k={ `UNIT_SKIN_${unit.uid}_${voice.sid}` } />
				}

				{ voice.isMarriage
					? <strong class="text-danger ps-4"><Locale k="UNIT_DIALOGUE_MARRIAGE" /></strong>
					: <Fragment />
				}
				{ IsMissing
					? <span class="badge bg-danger ms-3"><Locale k="UNIT_DIALOGUE_EMPTY" /></span>
					: IsPartial
						? <span class="badge bg-warning text-dark ms-3"><Locale k="UNIT_DIALOGUE_MISSING" /></span>
						: <Fragment />
				}
			</div>
			<div id={ collapseId } class="collapse">
				<div class="card-body">
					{ TypeList.map(type => <DialogueRow
						unitId={ unitId }
						isSkin={ !voice.isDef }
						type={ type }
						dialogue={ Dialogue[type] }
						lang={ props.lang }
					/>) }
				</div>
			</div>
		</div>
		: <Fragment />;
};
export default UnitDialogue;

// src/pages/Units/UnitDialogue.vue
<template>
	<b-card v-if="IsVoiceAvailable" class="mt-2 text-left" no-body :lang="lang">
		<b-card-header v-b-toggle:[CollapseKey]>
			<locale v-if="voice.sid === null" :k="`UNIT_${unit.uid}`" />
			<locale v-else :k="`UNIT_SKIN_${unit.uid}_${voice.sid}`" />

			<strong v-if="voice.isMarry" class="text-danger pl-4">
				<locale k="UNIT_DIALOGUE_MARRIAGE" />
			</strong>
			<b-badge v-if="IsMissing" variant="danger" class="ml-3">
				<locale k="UNIT_DIALOGUE_EMPTY" />
			</b-badge>
			<b-badge v-else-if="IsPartial" variant="warning" class="ml-3">
				<locale k="UNIT_DIALOGUE_MISSING" />
			</b-badge>
		</b-card-header>
		<b-collapse :id="CollapseKey">
			<b-card-body>
				<dialogue-row
					v-for="type in TypeList"
					:key="`dialogue-${unitId}-${type}`"
					:unit-id="unitId"
					:is-skin="!voice.isDef"
					:type="type"
					:dialogue="Dialogue[type]"
					:lang="lang"
				/>
			</b-card-body>
		</b-collapse>
	</b-card>
	<b-card v-else class="mt-2 text-left unit-dialogue-empty" no-body>
		<b-card-header>
			<locale v-if="voice.sid === null" :k="`UNIT_${unit.uid}`" />
			<locale v-else :k="`UNIT_SKIN_${unit.uid}_${voice.sid}`" />

			<b-badge variant="secondary" class="ml-3">
				<locale k="UNIT_DIALOGUE_VOICELESS" />
			</b-badge>
		</b-card-header>
	</b-card>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import { Prop, Watch, PropSync } from "vue-property-decorator";

import { SkinInfo } from "@/libs/Types";

import { RawUnitDialogue, RawUnitDialogueEntity, UnitDialogueDataType } from "@/libs/Types/Dialogue";
import DialogueDB from "@/libs/DB/Dialogue";

import { Unit } from "@/libs/Types/Unit";

import DialogueRow from "./DialogueRow.vue";

interface VoiceItem extends SkinInfo {
	id: number;
	isDef: boolean;
	isPro: boolean;
	isMarry: boolean;
}

@Component({
	components: {
		DialogueRow,
	},
})
export default class UnitDialogue extends Vue {
	private internalDialogueDB: Record<keyof UnitDialogueDataType, RawUnitDialogue | null> = {
		ko: null,
		jp: null,
	};

	private get DialogueDBKO () {
		if (this.internalDialogueDB.ko) return this.internalDialogueDB.ko;
		return DialogueDB("ko", (x) => {
			this.internalDialogueDB.ko = x;
		});
	}

	private get DialogueDBJP () {
		if (this.internalDialogueDB.jp) return this.internalDialogueDB.jp;
		return DialogueDB("jp", (x) => {
			this.internalDialogueDB.jp = x;
		});
	}

	private DialogueDB (type: keyof UnitDialogueDataType) {
		switch (type) {
			case "ko": return this.DialogueDBKO;
			case "jp": return this.DialogueDBJP;
		}
		return null;
	}

	@Prop({
		type: Object,
		required: true,
	})
	private unit!: Unit;

	@Prop({
		type: Object,
		required: true,
	})
	private voice!: VoiceItem;

	@Prop({
		type: Number,
		required: true,
	})
	private id!: number;

	@Prop({
		type: String,
		required: true,
	})
	private lang!: keyof UnitDialogueDataType;

	private uid: number = Math.random();

	private get CollapseKey () {
		return `dialogue-${this.uid}`;
	}

	private get TypeList (): Array<keyof RawUnitDialogueEntity> {
		const db = this.DialogueDB(this.lang);
		if (!db) return [];

		if (this.unit.uid in db) {
			const key = ((v) => {
				if (v.isMarry) return "M";
				if (v.isPro) return "P";
				if (v.isDef) return "0";
				return v.id.toString();
			})(this.voice);

			if (key in db[this.unit.uid]) {
				const diag = db[this.unit.uid][key];
				return Object.keys(diag) as Array<keyof RawUnitDialogueEntity>;
			}
		}

		return [
			...(this.voice.isDef && !this.voice.isMarry ? ["Join"] : []),
			"SquadJoin",
			"Leader",

			"SortiePick",
			"StageStart",
			"Retreat",
			"SearchStart",
			"SearchEnd",

			"BattleFocus",
			"ActionApprove",
			"SpSkill",
			"SpSkill_1",
			"SpSkill_2",
			"SpSkill_3",
			"SpSkill_4",
			"SpSkill_5",
			"SpSkill_6",
			"SpSkill_7",
			"SpSkill_8",
			"SpSkill_9",
			"Retire",
			"Repair",
			"Reinforce",
			"ItemEquip",
			"CoreLink",
			"PresentGet",

			"Login",
			"Idle_01_01",
			"Idle_01_02",
			"Idle_01_03",
			"SPIdle_01_01",
			"Idle_02_01",
			"Idle_03_01",
			"Idle_04_01",
			"SPIdle_02_01",

			"Oath",
			"OathIdle_01",
			"MVP",
		] as Array<keyof RawUnitDialogueEntity>;
	}

	private get Dialogue () {
		const db = this.DialogueDB(this.lang);
		if (db && this.unit.uid in db) {
			const key = ((v) => {
				if (v.isMarry) return "M";
				if (v.isPro) return "P";
				if (v.isDef) return "0";
				return v.id.toString();
			})(this.voice);

			if (key in db[this.unit.uid]) {
				const diag = db[this.unit.uid][key];
				return diag;
			}
		}
		return {
			Join: "???",
			SquadJoin: "???",
			Leader: "???",
			SortiePick: "???",
			StageStart: "???",
			Retreat: "???",
			SearchStart: "???",
			SearchEnd: "???",
			BattleFocus: "???",
			ActionApprove: "???",
			SpSkill: "???",
			SpSkill_2: "???",
			SpSkill_3: "???",
			SpSkill_4: "???",
			SpSkill_5: "???",
			Retire: "???",
			Repair: "???",
			Reinforce: "???",
			ItemEquip: "???",
			CoreLink: "???",
			PresentGet: "???",
			Login: "???",
			Idle_01_01: "???",
			Idle_01_02: "???",
			Idle_01_03: "???",
			SPIdle_01_01: "???",
			Idle_02_01: "???",
			Idle_03_01: "???",
			Idle_04_01: "???",
			SPIdle_02_01: "???",
			Oath: "???",
			OathIdle_01: "???",
			MVP: "???",
		};
	}

	private get IsVoiceAvailable () {
		/*
		if (!(this.unit.id in UnitDialogueData))
			return (this.voice.isMarry && this.unit.marry) || !this.voice.isMarry;

		const key = ((v) => {
			if (v.isMarry) return "M";
			if (v.isPro) return "P";
			if (v.isDef) return "0";
			return v.id.toString();
		})(this.voice);
		if (key in UnitDialogueData[this.unit.id])
			return true;

		return false;
		*/
		return this.voice.V;
	}

	private get IsMissing () {
		const db = this.DialogueDB(this.lang);
		if (!db) return [];

		const AllEmpty = (d: Partial<RawUnitDialogueEntity>) => Object.keys(d).every(x => !d[x as keyof RawUnitDialogueEntity]);
		return !(this.unit.uid in db) || AllEmpty(this.Dialogue);
	}

	private get IsPartial () {
		const db = this.DialogueDB(this.lang);
		if (!db) return [];

		const HasEmpty = (d: Partial<RawUnitDialogueEntity>) => Object.keys(d).some(x => !d[x as keyof RawUnitDialogueEntity]);
		return !(this.unit.uid in db) || HasEmpty(this.Dialogue);
	}

	private get unitId () {
		const uid = this.unit.uid || "";
		const postfix = (() => {
			if (this.voice.isMarry) return "_Marriage";
			if (this.voice.isDef) return "";
			if (this.voice.isPro) return "_PS1";
			return "_NS" + this.id;
		})();

		return `${uid}${postfix}`;
	}
}
</script>

<style lang="scss">
.unit-dialogue-empty {
	opacity: 0.5;
}
</style>
