// src/routes/units/view/index.tsx
import { Fragment, FunctionalComponent, h } from "preact";
import { route } from "preact-router";
import Decimal from "decimal.js";

import { SelectOption } from "@/types/Helper";
import { ACTOR_GRADE } from "@/types/Enums";
import { LinkBonusType, Unit, UnitSkin } from "@/types/DB/Unit";
import { FilterableEquip } from "@/types/DB/Equip.Filterable";
import { UnitDialogueDataType } from "@/types/DB/Dialogue";

import { ObjectState, objState } from "@/libs/State";
import { AssetsRoot, ImageExtension, RarityDisplay, UnitClassDisplay, UnitRoleDisplay } from "@/libs/Const";
import { isActive } from "@/libs/Functions";
import { GetRequireResource } from "@/libs/Cost";
import EntitySource from "@/libs/EntitySource";
import { GetLinkBonus } from "@/libs/LinkBonus";
import { SetMeta, UpdateTitle } from "@/libs/Site";

import Loader, { DBSourceConverter, GetJson, StaticDB } from "@/components/loader";
import Locale, { LocaleGet } from "@/components/locale";
import Icon from "@/components/bootstrap-icon";
import RarityBadge from "@/components/rarity-badge";
import UnitFace from "@/components/unit-face";
import UnitBadge from "@/components/unit-badge";
import ElemIcon from "@/components/elem-icon";
import SourceBadge from "@/components/source-badge";

import SkinView from "../components/skin-view";
import SkillTable from "../components/skill-table";
import UnitDialogue, { VoiceItem } from "../components/unit-dialogue";

import "./style.scss";

type TabTypes = "basic" | "skills" | "dialogue";

interface SkinItem extends UnitSkin {
	isDef: boolean;
	isPro: boolean;
}

interface SubpageProps {
	display: boolean;
	unit: Unit;
	skinIndex: ObjectState<number>;
	SkinList: SkinItem[];
}

const BasicTab: FunctionalComponent<SubpageProps> = ({ display, unit, skinIndex, SkinList }) => {
	const FilterableEquipDB = GetJson<FilterableEquip[]>(StaticDB.FilterableEquip, DBSourceConverter);

	const CurrentSkinPostfix = ((): string => {
		const skin = SkinList[skinIndex.value];
		if (!skin || skin.isDef) return "N";
		if (skin.isPro) return "PS1";
		return `NS${skin.sid}`;
	})();

	const ExclusiveEquip = FilterableEquipDB
		.filter(x => x.limit && x.limit.some(y => y === unit.uid))
		.map(x => ({
			equip: x,
			url: `/equips/${x.fullKey}`,
		}));

	const CraftTime = ((): string => {
		const duration = unit.craft;
		if (!duration) return "-";

		const h = Math.floor(duration / 3600);
		const m = Math.floor(duration / 60) % 60;
		const s = duration % 60;
		return `${(`0${h}`).substr(-2)}:${(`0${m}`).substr(-2)}:${(`0${s}`).substr(-2)}`;
	})();

	const Favor = {
		clear: Decimal.mul(unit.favor.clear, 5)
			.floor()
			.div(100)
			.toNumber(),
		death: Decimal.mul(unit.favor.death, 2).toNumber(),
		assistant: Decimal.mul(unit.favor.assistant, 1).toNumber(),
	};

	return <div style={ { display: display ? "" : "none" } }>
		{/* 스킨, 번호, 소속, 등급, 승급, 유형, 역할 */ }
		<ul class="nav nav-tabs unit-display-tabs justify-content-start">
			{ SkinList.map((skin, index) => <li class="nav-item">
				<a
					href="#"
					class={ [
						"nav-link",
						isActive(skinIndex.value === index),
						skinIndex.value === index ? `rarity-${skin.isPro ? "SS" : unit.rarity}-force text-dark` : "text-dark",
					].join(" ") }
					onClick={ (e): void => {
						e.preventDefault();
						skinIndex.set(index);
					} }
				>
					{ skin.isPro
						? index === skinIndex.value
							? <span class="badge bg-light text-dark me-1">
								<Locale k="UNIT_CARD_PROMOTION_BADGE" p={ ["SS"] } />
							</span>
							: <RarityBadge rarity="SS" class="me-1">
								<Locale k="UNIT_CARD_PROMOTION_BADGE" p={ ["SS"] } />
							</RarityBadge>
						: <Fragment /> }

					<span>
						{ skin.sid === null
							? <Locale k={ `UNIT_${unit.uid}` } />
							: <Locale k={ `UNIT_SKIN_${unit.uid}_${skin.sid}` } /> }
					</span>
				</a>
			</li>) }
		</ul>

		<div class="row">
			<div class="col-12 col-md-3">
				{ SkinList[skinIndex.value]
					? <SkinView unit={ unit } skin={ SkinList[skinIndex.value] } collapsed detailable />
					: <Fragment /> }
			</div>
			<div class="mt-3 col-md-9 col-12">
				<div class="row">
					<div class="col" />
					<div class="col-auto">
						<UnitFace uid={ unit.uid } skin={ SkinList[skinIndex.value].sid || 0 } size="88" />
					</div>
					<div class="col-auto">
						<UnitFace
							uid={ `TbarIcon_${unit.uid}_${CurrentSkinPostfix}` }
							skin={ SkinList[skinIndex.value].sid || 0 }
							sd
							size="88"
						/>
					</div>
					<div class="col" />
				</div>

				<div class="card bg-dark text-light introduce-text mx-3 mt-3 p-3">
					<Locale k={ `UNIT_INTRO_${unit.uid}` } />
				</div>

				{ ExclusiveEquip.length > 0
					? <div class="alert alert-primary mt-3">
						<div>
							<Locale k="UNIT_VIEW_PRIVATE_EQUIP" />
						</div>
						{ ExclusiveEquip.map(limited => <a
							href={ limited.url }
							onClick={ (e): void => {
								e.preventDefault();
								route(limited.url);
							} }
						>
							{/* <drop-equip class="limited-item-card" :equip="limited.equip" /> */ }
						</a>) }
					</div>
					: <Fragment />
				}

				<div class="container table-unit-modal my-3">
					<div class="row text-center row-cols-2 row-cols-md-4">
						<div class="col bg-dark text-light"><Locale k="UNIT_VIEW_DICTNO" /></div>
						<div class="col">
							<small>No.&nbsp;</small>
							<strong>{ unit.id }</strong>
						</div>
						<div class="col bg-dark text-light"><Locale k="UNIT_VIEW_FACTION" /></div>
						<div class="col">
							<span class="break-keep">
								<Locale k={ `UNIT_GROUP_${unit.group}` } />
							</span>
						</div>
						<div class="col bg-dark text-light"><Locale k="UNIT_VIEW_GRADE" /></div>
						<div class="col">
							<RarityBadge rarity={ unit.rarity } size="medium">
								<Locale k="COMMON_UNIT_GRADE_FORMAT" p={ [RarityDisplay[unit.rarity]] } />
							</RarityBadge>
						</div>
						<div class="col bg-dark text-light"><Locale k="UNIT_VIEW_PROMOTION" /></div>
						<div class="col">
							{ unit.promotions
								? unit.promotions.map(pro => <RarityBadge rarity={ pro } size="medium">
									<Locale k="UNIT_VIEW_PROMOTION_BADGE" p={ [RarityDisplay[pro]] } />
								</RarityBadge>)
								: <span class="text-secondary"><Locale k="UNIT_VIEW_PROMOTION_BADGE_EMPTY" /></span>
							}
						</div>
						<div class="col bg-dark text-light"><Locale k="UNIT_VIEW_TYPE" /></div>
						<div class="col">
							<UnitBadge type={ unit.type } size="large" transparent black />
						</div>
						<div class="col bg-dark text-light"><Locale k="UNIT_VIEW_ROLE" /></div>
						<div class="col">
							<UnitBadge role={ unit.role } size="large" transparent black />
						</div>
						<div class="col bg-dark text-light"><Locale k="UNIT_VIEW_HEIGHT" /></div>
						<div class="col">{ unit.height }</div>
						<div class="col bg-dark text-white"><Locale k="UNIT_VIEW_WEIGHT" /></div>
						<div class="col">{ unit.weight }</div>
						<div class="col bg-dark text-white"><Locale k="UNIT_VIEW_BATTLESTYLE" /></div>
						<div class="col">{ unit.weapon1 }</div>
						<div class="col bg-dark text-white"><Locale k="UNIT_VIEW_WEAPON" /></div>
						<div class="col">{ unit.weapon2 }</div>
					</div>
				</div>

				<table class="table table-bordered table-fixed text-center table-unit-modal">
					<thead class="thead-dark">
						<tr>
							<th><Locale k="UNIT_VIEW_FAVOR_PRESENT" /></th>
							<th><Locale k="UNIT_VIEW_FAVOR_VICTORY" /></th>
							<th class="d-none d-md-table-cell"><Locale k="UNIT_VIEW_FAVOR_RETIRE" /></th>
							<th class="d-none d-md-table-cell"><Locale k="UNIT_VIEW_FAVOR_ASSISTANT" /></th>
						</tr>
					</thead>
					<tbody>
						<tr class="text-center">
							<td>
								<Locale k="UNIT_VIEW_FAVOR_MULTIPLY" p={ [unit.favor.present.toFixed(2)] } />
							</td>
							<td>
								<span class="badge bg-danger"><Locale k="UNIT_VIEW_FAVOR_P" p={ [Favor.clear] } /></span>
							</td>
							<td class="d-none d-md-table-cell">
								<span class="badge bg-danger"><Locale k="UNIT_VIEW_FAVOR_M" p={ [Favor.death] } /></span>
							</td>
							<td class="d-none d-md-table-cell">
								<span class="badge bg-danger"><Locale k="UNIT_VIEW_FAVOR_P" p={ [Favor.assistant] } /></span>
							</td>
						</tr>
						<tr class="d-md-none">
							<th class="bg-dark text-white"><Locale k="UNIT_VIEW_FAVOR_RETIRE" /></th>
							<th class="bg-dark text-white"><Locale k="UNIT_VIEW_FAVOR_ASSISTANT" /></th>
						</tr>
						<tr class="d-md-none text-center">
							<td>
								<span class="badge bg-danger"><Locale k="UNIT_VIEW_FAVOR_M" p={ [Favor.death] } /></span>
							</td>
							<td>
								<span class="badge bg-danger"><Locale k="UNIT_VIEW_FAVOR_P" p={ [Favor.assistant] } /></span>
							</td>
						</tr>
					</tbody>
				</table>

				<table class="table table-bordered table-fixed text-center table-unit-modal">
					<thead class="thead-dark">
						<tr>
							<th><Locale k="UNIT_VIEW_DROPS" /></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="px-0 py-1 drop-list">
								{ unit.source.length === 0 && !unit.craft
									? <span class="text-secondary">
										<Locale k="UNIT_VIEW_DROPS_EMPTY" />
									</span>
									: <Fragment>
										{ unit.craft
											? <span class="badge bg-dark my-1">
												<Icon icon="hammer" class="me-1" />
												<Locale k="UNIT_VIEW_DROPS_CREATIONTIME" />
												<span class="ms-1">{ CraftTime }</span>
											</span>
											: <Fragment />
										}

										{ unit.source.map((area, aindex) => <div>
											{ unit.craft || aindex > 0 ? <hr class="my-1" /> : <Fragment /> }
											{ area.length > 0 && area[0].IsEvent
												? <h6 style="font-weight: bold">
													<Locale k={ area[0].EventName } />
												</h6>
												: area.length > 0 && area[0].IsChallenge
													? <h6 style="font-weight: bold">
														<Locale k={ `COMMON_CHALLENGE_${area[0].ChallengeName}` } />
													</h6>
													: area.length > 0 && area[0].IsSubStory
														? <h6 style="font-weight: bold">
															<Locale k="COMMON_SOURCE_SUBSTORY_SINGLE" />
														</h6>
														: <Fragment />
											}

											{ area.map(source => <SourceBadge class="my-1" source={ source } linked />) }
										</div>) }
									</Fragment>
								}
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>;
};

const SkillTab: FunctionalComponent<SubpageProps> = ({ display, unit }) => {
	const CurrentResists = unit.stat[0].Resist;

	const linkCount = objState<number>(5);
	const LinkBonus = unit.linkBonus
		.filter(x => x)
		.map(x => GetLinkBonus(x, linkCount.value));

	const FullLinkBonus = unit.fullLinkBonus.map(x => GetLinkBonus(x, 1));
	const fullLinkBonus = objState<LinkBonusType>("");

	const CostRarityList = ((): SelectOption<ACTOR_GRADE>[] => {
		const list = [{
			text: <Locale k="COMMON_UNIT_GRADE_FORMAT" p={ [RarityDisplay[unit.rarity]] } />,
			value: unit.rarity,
		}];

		if (unit.promotions) {
			list.push(...unit.promotions.map(x => ({
				text: <Locale k="UNIT_CARD_PROMOTION_BADGE" p={ [RarityDisplay[x]] } />,
				value: x,
			})));
		}

		return list;
	})();
	const costRarity = objState<ACTOR_GRADE>(unit.rarity);

	function CostClass (level: number, value: number): string {
		if (value === 0) return "text-secondary";
		if (fullLinkBonus.value.startsWith("Cost_") && level === 5)
			return "text-primary";
		return "";
	}

	const CostTable = GetRequireResource(
		costRarity.value,
		unit.type,
		unit.role,
		unit.body,
		fullLinkBonus.value,
	);

	const SkillPowerBonus = ((): number => {
		let bonus = new Decimal(0);

		if (linkCount.value === 5) {
			if (fullLinkBonus.value === "Skill_2") bonus = bonus.add(2);
			if (fullLinkBonus.value === "Skill_5") bonus = bonus.add(5);
			if (fullLinkBonus.value === "Skill_10") bonus = bonus.add(10);
			if (fullLinkBonus.value === "Skill_15") bonus = bonus.add(15);
			if (fullLinkBonus.value === "Skill_20") bonus = bonus.add(20);
			if (fullLinkBonus.value === "Skill_25") bonus = bonus.add(25);
			if (fullLinkBonus.value === "Skill_30") bonus = bonus.add(30);
			if (fullLinkBonus.value === "Skill_35") bonus = bonus.add(35);
		}

		if (unit.linkBonus.includes("Skill_2")) bonus = bonus.add(Decimal.mul(2, linkCount.value));
		if (unit.linkBonus.includes("Skill_5")) bonus = bonus.add(Decimal.mul(5, linkCount.value));
		if (unit.linkBonus.includes("Skill_10")) bonus = bonus.add(Decimal.mul(10, linkCount.value));
		if (unit.linkBonus.includes("Skill_15")) bonus = bonus.add(Decimal.mul(15, linkCount.value));
		if (unit.linkBonus.includes("Skill_20")) bonus = bonus.add(Decimal.mul(20, linkCount.value));
		if (unit.linkBonus.includes("Skill_25")) bonus = bonus.add(Decimal.mul(25, linkCount.value));
		if (unit.linkBonus.includes("Skill_30")) bonus = bonus.add(Decimal.mul(30, linkCount.value));
		if (unit.linkBonus.includes("Skill_35")) bonus = bonus.add(Decimal.mul(35, linkCount.value));

		return bonus.toNumber();
	})();

	return <div style={ { display: display ? "" : "none" } }>
		<div class="row">
			<div class="col-12 col-md-4">
				<table class="table table-bordered table-fixed text-center table-unit-modal">
					<thead class="thead-dark">
						<tr>
							<th class="text-center">
								<ElemIcon elem="fire" />
								{ CurrentResists.fire } %
							</th>
							<th class="text-center">
								<ElemIcon elem="ice" />
								{ CurrentResists.ice } %
							</th>
							<th class="text-center">
								<ElemIcon elem="lightning" />
								{ CurrentResists.lightning } %
							</th>
						</tr>
						<tr>
							<th colSpan={ 3 }>
								<Locale k="UNIT_VIEW_LINKBONUS" />
								<div class="btn-group btn-group-sm ms-3">
									{ new Array(6)
										.fill(0)
										.map((_, i) => <button
											class={ `btn btn-${linkCount.value === i ? "primary" : "light"}` }
											onClick={ (): void => linkCount.set(i) }
										>{ i }</button>) }
								</div>
							</th>
						</tr>
					</thead>
					<tbody>
						{ LinkBonus.map((lb) => <tr>
							<td colSpan={ 3 }>
								<Locale k={ lb.Name } />
								<span class="d-inline-block ps-1">
									{ lb.Prefix }
									<b class="text-danger">{ lb.Value }</b>
									{ lb.Postfix }
								</span>
							</td>
						</tr>) }
					</tbody>
				</table>
			</div>

			<div class="col-12 col-md-4 fulllink-table">
				<table class="table table-bordered table-fixed text-start table-unit-modal">
					<thead class="thead-dark">
						<tr>
							<th class="text-center"><Locale k="UNIT_VIEW_FULL_LINKBONUS" /></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<Locale k="LINKBONUS_NONE" />
								<div class="form-check float-end">
									<input
										class="form-check-input"
										type="radio"
										checked={ fullLinkBonus.value === "" }
										onChange={ (): void => fullLinkBonus.set("") }
									/>
								</div>
							</td>
						</tr>
						{ FullLinkBonus.map((fl) => <tr>
							<td>
								<Locale k={ fl.Name } />
								<span class="d-inline-block ps-1">
									{ fl.Prefix }
									<b class="text-danger">{ fl.Value }</b>
									{ fl.Postfix }
								</span>

								<div class="form-check float-end">
									<input
										class="form-check-input"
										type="radio"
										checked={ fullLinkBonus.value === fl.Key }
										onChange={ (): void => fullLinkBonus.set(fl.Key) }
									/>
								</div>
							</td>
						</tr>) }
					</tbody>
				</table>
			</div>

			<div class="col-12 col-md-4">
				<table class="table table-bordered table-fixed text-center table-unit-modal">
					<thead class="thead-dark">
						<tr>
							<th colSpan={ 4 }>
								<Locale k="UNIT_VIEW_COST" />
								{ CostRarityList.length > 1
									? <select
										class="form-select form-select-sm table-unit-rarity-select"
										value={ costRarity.value }
										onChange={ (e): void => {
											costRarity.set(
												parseInt((e.target as HTMLSelectElement).value, 10) as ACTOR_GRADE,
											);
										} }
									>
										{ CostRarityList.map(option => <option value={ option.value }>
											{ option.text }
										</option>) }
									</select>
									: <Fragment />
								}
							</th>
						</tr>
						<tr>
							<th><Locale k="UNIT_VIEW_COST_LINKS" /></th>
							<th><Locale k="COMMON_RES_PARTS" /></th>
							<th><Locale k="COMMON_RES_NUTRIENTS" /></th>
							<th><Locale k="COMMON_RES_POWER" /></th>
						</tr>
					</thead>
					<tbody>
						{ new Array(6)
							.fill(0)
							.map((_, i) => <tr class="text-center">
								<th class="bg-dark text-light">{ i }</th>
								<td class={ CostClass(i, CostTable.metal[i]) }>{ CostTable.metal[i] }</td>
								<td class={ CostClass(i, CostTable.nutrient[i]) }>{ CostTable.nutrient[i] }</td>
								<td class={ CostClass(i, CostTable.power[i]) }>{ CostTable.power[i] }</td>
							</tr>)
						}
					</tbody>
				</table>
			</div>
		</div>

		<SkillTable
			unit={ unit }
			buffBonus={ linkCount.value === 5 && fullLinkBonus.value.startsWith("Buff_") }
			skillBonus={ SkillPowerBonus }
			rangeBonus={ linkCount.value === 5 && fullLinkBonus.value.startsWith("Range_") }
		/>
	</div>;
};

const DialogueTab: FunctionalComponent<SubpageProps> = ({ display, unit, SkinList }) => {
	const dialogueLang = objState<keyof UnitDialogueDataType>("ko");

	const VoiceList: VoiceItem[] = [
		{
			id: 0,
			...SkinList[0],
			isMarriage: false,
		},
		...(unit.marriageVoice
			? [{
				id: 0,
				...SkinList[0],
				isMarriage: true,
			}]
			: []),
		...SkinList
			.slice(1)
			.map((x, i) => ({
				id: i + 1,
				...x,
				isMarriage: false,
			})),
	];

	return <div style={ { display: display ? "" : "none" } }>
		<div class="btn-group">
			<button
				class={ `btn btn-outline-primary ${isActive(dialogueLang.value === "ko")}` }
				onClick={ (): void => dialogueLang.set("ko") }
			>한국어</button>
			<button
				class={ `btn btn-outline-primary ${isActive(dialogueLang.value === "jp")}` }
				onClick={ (): void => dialogueLang.set("jp") }
			>日本語</button>
		</div>

		{ VoiceList.map(voice => <UnitDialogue
			unit={ unit }
			voice={ voice }
			id={ voice.id }
			lang={ dialogueLang.value }
		/>) }
	</div>;
};

interface UnitsViewProps {
	uid: string;
}

const View: FunctionalComponent<UnitsViewProps> = (props) => {
	const DisplayTab = objState<TabTypes>("basic");

	function GoBack (): void {
		window.history.back();
	}

	const skinIndex = objState<number>(0);

	return <Loader json={ [StaticDB.FilterableEquip, `unit/${props.uid}`] } content={ ((): preact.VNode => {
		const unit = ((): Unit => {
			const raw = GetJson<Unit>(`unit/${props.uid}`);
			return {
				...raw,
				source: raw.source
					.map(x => (x as unknown as string[]).map(y => new EntitySource(y))),
			};
		})();

		const SkinList = ((): SkinItem[] => {
			const list: SkinItem[] = [];

			const skin = unit.skins;
			if (!skin) return list;

			// 캐릭터 기본 스킨
			list.push({
				...skin,
				// t: unit.name,
				isDef: true,
				isPro: false,
				// name: "",
				// desc: "",
			});

			if (skin.skins) {
				list.push(...skin.skins.map((x) => {
					return {
						...x,
						isDef: false,
						isPro: false,
					};
				}));
			}

			if (skin.P) {
				list.push({
					...skin.P,
					isDef: false,
					isPro: true,
				});
			}

			return list;
		})();

		SetMeta(
			["description", "twitter:description"],
			`${RarityDisplay[unit.rarity]}급 ${UnitClassDisplay[unit.type]} ${UnitRoleDisplay[unit.role]} ` +
			`${LocaleGet(`UNIT_${unit.uid}`)}의 정보입니다. ` +
			"기본 정보, 링크/풀링크 보너스, 스킬 정보, 대사를 확인할 수 있으며, 스테이터스 계산기를 이용할 수 있습니다.",
		);
		SetMeta(
			["twitter:image", "og:image"],
			`${AssetsRoot}/${ImageExtension()}/full/${(`00${unit.id}`).substr(-3)}.${ImageExtension()}`,
		);
		SetMeta(
			"keywords",
			`,${[LocaleGet(`UNIT_${unit.uid}`), LocaleGet(`UNIT_SHORT_${unit.uid}`)].unique().join(",")}`,
			true,
		);
		UpdateTitle(LocaleGet("MENU_UNITS"), LocaleGet(`UNIT_${unit.uid}`));

		return <div class="unit-view">
			<div class="row">
				<div class="col-12 col-md-auto text-start">
					<button class="btn btn-dark" onClick={ (): void => GoBack() }>
						<Locale k="COMMON_BACK" />
					</button>
				</div>
				<div class="col">
					<ul class="nav nav-tabs unit-display-tabs mb-3 justify-content-end">
						<li class="nav-item">
							<a
								href="#"
								class={ `nav-link text-dark ${isActive(DisplayTab.value === "basic")}` }
								onClick={ (e): void => {
									e.preventDefault();
									DisplayTab.set("basic");
								} }
							>
								<Icon icon="person-square" class="me-1" />
								<Locale k="UNIT_VIEW_TAB_BASICINFO" />
							</a>
						</li>
						<li class="nav-item">
							<a
								href="#"
								class={ `nav-link text-dark ${isActive(DisplayTab.value === "skills")}` }
								onClick={ (e): void => {
									e.preventDefault();
									DisplayTab.set("skills");
								} }
							>
								<Icon icon="lightning-fill" class="me-1" />
								<Locale k="UNIT_VIEW_TAB_SKILLS" />
							</a>
						</li>
						<li class="nav-item">
							<a
								href="#"
								class={ `nav-link text-dark ${isActive(DisplayTab.value === "dialogue")}` }
								onClick={ (e): void => {
									e.preventDefault();
									DisplayTab.set("dialogue");
								} }
							>
								<Icon icon="chat-text-fill" class="me-1" />
								<Locale k="UNIT_VIEW_TAB_DIALOGUE" />
							</a>
						</li>
					</ul>
				</div>
			</div>

			<BasicTab display={ DisplayTab.value === "basic" } unit={ unit } skinIndex={ skinIndex } SkinList={ SkinList } />
			<SkillTab display={ DisplayTab.value === "skills" } unit={ unit } skinIndex={ skinIndex } SkinList={ SkinList } />
			<DialogueTab display={ DisplayTab.value === "dialogue" } unit={ unit } skinIndex={ skinIndex } SkinList={ SkinList } />
		</div>;
	}) } />;
};
export default View;

// src/pages/Units/View.vue
<template>
	<div class="unit-view">
		<b-row>
			<b-col cols="12" md="auto" class="text-left">
				<b-button variant="dark" @click="GoBack()">뒤로</b-button>
			</b-col>
			<b-col>
				<b-tabs nav-class="unit-display-tabs mb-3" align="right">
					<b-tab title-link-class="text-dark" :active="displayTab === 'texts'" @click="displayTab = 'texts'">
						<template #title>
							<b-icon-person-square class="mr-1" />
							기본정보
						</template>
					</b-tab>
					<b-tab title-link-class="text-dark" :active="displayTab === 'information'" @click="displayTab = 'information'">
						<template #title>
							<b-icon-lightning-fill class="mr-1" />
							링크/스킬
						</template>
					</b-tab>
					<b-tab title-link-class="text-dark" :active="displayTab === 'dialogue'" @click="displayTab = 'dialogue'">
						<template #title>
							<b-icon-chat-text-fill class="mr-1" />
							대사
						</template>
					</b-tab>
					<b-tab title-link-class="text-dark" :active="displayTab === 'status'" @click="displayTab = 'status'">
						<template #title>
							<b-icon-calculator class="mr-1" />
							스테이터스
						</template>
					</b-tab>
				</b-tabs>
			</b-col>
		</b-row>

		<div v-show="displayTab === 'texts'">
			<!-- 스킨, 번호, 소속, 등급, 승급, 유형, 역할 -->
			<b-tabs v-model="skinIndex" nav-class="unit-skin-tabs">
				<b-tab
					v-for="(skin, index) in SkinList"
					:key="`unit-skin-${index}`"
					:title-link-class="index === skinIndex ? `rarity-${skin.isPro ? 'SS' : unit.rarity}-force text-dark` : 'text-dark'"
					:active="index === 0"
				>
					<template #title>
						<template v-if="skin.isPro">
							<b-badge v-if="index === skinIndex" variant="light">SS 승급</b-badge>
							<rarity-badge v-else rarity="SS">SS 승급</rarity-badge>
							{{ skin.t }}
						</template>
						<template v-else>{{ skin.t }}</template>
					</template>
				</b-tab>
			</b-tabs>

			<b-row>
				<b-col cols="12" md="3">
					<unit-skin-view v-if="SkinList[skinIndex]" :unit="unit" :skin="SkinList[skinIndex]" collapsed detailable />
				</b-col>

				<b-col cols="12" md="9">
					<b-card no-body bg-variant="dark" text-variant="light" class="mt-4 introduce-text p-3">
						{{ unit.introduce }}
					</b-card>

					<b-alert v-if="unit.hasLimited" variant="primary" show class="mt-3">
						<div>이 전투원은 다음 전용장비를 갖고 있습니다.</div>
						<a :href="LimitedEquipURL" @click.prevent="GoTo(LimitedEquipURL)">
							<drop-equip class="limited-item-card" :equip="LimitedEquip" />
						</a>
					</b-alert>

					<b-container class="table-unit-modal mt-3 mb-3">
						<b-row cols="2" cols-md="4" class="text-center">
							<b-col class="bg-dark text-white">도감 번호</b-col>
							<b-col>
								<small>No.&nbsp;</small>
								<strong>{{ unit.id }}</strong>
							</b-col>
							<b-col class="bg-dark text-white">소속</b-col>
							<b-col>
								<span class="break-keep">{{ unit.group }}</span>
							</b-col>
							<b-col class="bg-dark text-white">등급</b-col>
							<b-col>
								<rarity-badge :rarity="unit.rarity" size="medium">{{ RarityName[unit.rarity] }} 등급</rarity-badge>
							</b-col>
							<b-col class="bg-dark text-white">승급</b-col>
							<b-col>
								<template v-if="unit.promotions">
									<rarity-badge v-for="pro in unit.promotions" :key="`unit-promotion-${pro}`" :rarity="pro" size="medium"
										>{{ RarityName[pro] }} 승급</rarity-badge
									>
								</template>
								<template v-else>
									<span class="text-secondary">승급 없음</span>
								</template>
							</b-col>
							<b-col class="bg-dark text-white">유형</b-col>
							<b-col>
								<unit-badge :type="unit.type" size="large" transparent black />
							</b-col>
							<b-col class="bg-dark text-white">역할</b-col>
							<b-col>
								<unit-badge :role="unit.role" size="large" transparent black />
							</b-col>
							<b-col class="bg-dark text-white">키</b-col>
							<b-col>{{ unit.height }}</b-col>
							<b-col class="bg-dark text-white">몸무게</b-col>
							<b-col>{{ unit.weight }}</b-col>
							<b-col class="bg-dark text-white">전투 스타일</b-col>
							<b-col>{{ unit.weapon1 }}</b-col>
							<b-col class="bg-dark text-white">무기</b-col>
							<b-col>{{ unit.weapon2 }}</b-col>
						</b-row>
					</b-container>

					<b-table-simple bordered fixed table-class="text-center table-unit-modal">
						<b-thead head-variant="dark">
							<b-tr>
								<b-th>선물</b-th>
								<b-th>웨이브 승리</b-th>
								<b-th class="d-none d-md-table-cell">사망</b-th>
								<b-th class="d-none d-md-table-cell">부관</b-th>
							</b-tr>
						</b-thead>
						<b-tbody>
							<b-tr class="text-center">
								<b-td>{{ unit.favor.present.toFixed(2) }}배</b-td>
								<b-td>
									<b-badge variant="danger">♥ 호감도 +{{ Favor.clear }}</b-badge>
								</b-td>
								<b-td class="d-none d-md-table-cell">
									<b-badge variant="danger">♥ 호감도 -{{ Favor.death }}</b-badge>
								</b-td>
								<b-td class="d-none d-md-table-cell">
									<b-badge variant="danger">♥ 호감도 +{{ Favor.assistant }}</b-badge>
								</b-td>
							</b-tr>
							<b-tr class="d-md-none">
								<b-th class="bg-dark text-white">사망</b-th>
								<b-th class="bg-dark text-white">부관</b-th>
							</b-tr>
							<b-tr class="d-md-none text-center">
								<b-td>
									<b-badge variant="danger">♥ 호감도 -{{ Favor.death }}</b-badge>
								</b-td>
								<b-td>
									<b-badge variant="danger">♥ 호감도 +{{ Favor.assistant }}</b-badge>
								</b-td>
							</b-tr>
						</b-tbody>
					</b-table-simple>

					<b-table-simple bordered fixed table-class="text-center table-unit-modal">
						<b-thead head-variant="dark">
							<b-tr>
								<b-th>획득처</b-th>
							</b-tr>
						</b-thead>
						<b-tbody>
							<b-tr>
								<b-td class="px-0 py-1 drop-list">
									<span v-if="unit.source.length === 0 && !unit.craftable" class="text-secondary">
										획득처 정보 없음 (제조 불가)
									</span>
									<template v-else>
										<b-badge v-if="unit.craftable" variant="dark" class="my-1">
											<b-icon-hammer class="mr-1" />
											제조 시간 {{ CraftTime }}
										</b-badge>

										<div v-for="(area, aindex) in unit.source" :key="`unit-view-source-${aindex}`">
											<hr v-if="unit.craftable || aindex > 0" class="my-1" />
											<h6 v-if="area.length > 0 && area[0].EventName" style="font-weight: bold">{{ area[0].EventName }}</h6>
											<source-badge
												v-for="(source, sindex) in area"
												:key="`unit-view-drop-${aindex}-${sindex}-${source}`"
												class="my-1"
												:source="source"
												linked
											/>
										</div>
									</template>
								</b-td>
							</b-tr>
						</b-tbody>
					</b-table-simple>
				</b-col>
			</b-row>
		</div>

		<div v-show="displayTab === 'information'">
			<b-row>
				<b-col cols="12" md="4">
					<b-table-simple bordered fixed table-class="text-center table-unit-modal">
						<b-thead head-variant="dark">
							<b-tr>
								<b-th class="text-center">
									<elem-icon elem="fire" />
									{{ CurrentResists.fire }} %
								</b-th>
								<b-th class="text-center">
									<elem-icon elem="ice" />
									{{ CurrentResists.ice }} %
								</b-th>
								<b-th class="text-center">
									<elem-icon elem="lightning" />
									{{ CurrentResists.lightning }} %
								</b-th>
							</b-tr>
							<b-tr>
								<b-th colspan="3">
									링크 보너스
									<b-form-select class="table-unit-link-select" size="sm" v-model="linkCount" :options="LinkCountList" />
								</b-th>
							</b-tr>
						</b-thead>
						<b-tbody>
							<b-tr v-for="(lb, lbIdx) in LinkBonus" :key="`unit-linkbonus-row-${lbIdx}`">
								<b-td colspan="3">
									{{ lb.Name }}
									<span class="d-inline-block">
										{{ lb.Prefix }}<b class="text-danger">{{ lb.Value }}</b
										>{{ lb.Postfix }}
									</span>
								</b-td>
							</b-tr>
						</b-tbody>
					</b-table-simple>
				</b-col>
				<b-col cols="12" md="4" class="fulllink-table">
					<b-table-simple bordered fixed table-class="text-left table-unit-modal">
						<b-thead head-variant="dark">
							<b-tr>
								<b-th class="text-center">풀링크 보너스</b-th>
							</b-tr>
						</b-thead>
						<b-tbody>
							<b-tr>
								<b-td>
									없음
									<b-radio class="float-right" value v-model="linkBonus" />
								</b-td>
							</b-tr>
							<b-tr v-for="(fl, flIdx) in FullLinkBonus" :key="`unit-fulllinkbonus-row-${flIdx}`">
								<b-td>
									{{ fl.Name }}
									<span class="d-inline-block">
										{{ fl.Prefix }}<b class="text-danger">{{ fl.Value }}</b
										>{{ fl.Postfix }}
									</span>
									<b-radio v-if="BonusSelectable(fl.Key)" class="float-right" :value="fl.Key" v-model="linkBonus" />
								</b-td>
							</b-tr>
						</b-tbody>
					</b-table-simple>
				</b-col>
				<b-col cols="12" md="4">
					<b-table-simple bordered fixed table-class="text-center table-unit-modal">
						<b-thead head-variant="dark">
							<b-tr>
								<b-th colspan="4">
									출격 비용
									<b-form-select
										v-if="CostRarityList.length > 1"
										class="table-unit-rarity-select"
										size="sm"
										v-model="costRarity"
										:options="CostRarityList"
									/>
								</b-th>
							</b-tr>
							<b-tr>
								<b-th>링크</b-th>
								<b-th>부품</b-th>
								<b-th>영양</b-th>
								<b-th>전력</b-th>
							</b-tr>
						</b-thead>
						<b-tbody>
							<b-tr v-for="i in 6" :key="`unit-modal-cost-${i}`" class="text-center">
								<b-th variant="dark">{{ i - 1 }}</b-th>
								<b-td :class="CostClass(i - 1, CostTable.metal[i - 1])">{{ CostTable.metal[i - 1] }}</b-td>
								<b-td :class="CostClass(i - 1, CostTable.nutrient[i - 1])">{{ CostTable.nutrient[i - 1] }}</b-td>
								<b-td :class="CostClass(i - 1, CostTable.power[i - 1])">{{ CostTable.power[i - 1] }}</b-td>
							</b-tr>
						</b-tbody>
					</b-table-simple>
				</b-col>
			</b-row>

			<unit-skill-table
				v-if="SkillsRaw"
				:skills="SkillsRaw"
				:skill-level.sync="skillLevel"
				:form-state.sync="formState"
				:rarity="unit.rarity"
				:buff-bonus="linkBonus.startsWith('Buff_')"
				:skill-bonus="SkillPowerBonus"
				:range-bonus="linkBonus.startsWith('Range_')"
			/>
		</div>
		<div v-show="displayTab === 'dialogue'">
			<b-alert variant="success" show>
				현재 대사 텍스트가 입력되지 않은 전투원이 매우 많습니다. 입력해야하는 대사 분량이 너무 많아 개발자 혼자 작업할 수가 없어 발생한
				문제입니다.<br />
				이 문제를 해결하고자 현재
				<a href="https://docs.google.com/spreadsheets/d/1TrLn5czFe2Ww1xg4HiFsDzZDcnphxV3AqP_DgNqaU00" target="_blank">전투원 대사 DB</a>의
				기여를 받고 있습니다. 많은 참여 부탁드립니다.
			</b-alert>
			<hr />

			<unit-dialogue v-for="(voice, keyid) in VoiceList" :key="`unit-view-text-voice-${keyid}`" :unit="unit" :voice="voice" :id="voice.id" />
		</div>
		<unit-stats v-show="displayTab === 'status'" :unit="unit" :serialized="statusSerialized" />
	</div>
</template>

<script lang="tsx">
import { Decimal } from "decimal.js";

import Vue from "vue";
import Component from "vue-class-component";
import { Prop, Watch, PropSync } from "vue-property-decorator";

import StoreModule from "@/libs/Store";

import NodeRenderer from "@/components/NodeRenderer.vue";
import UnitFace from "@/components/UnitFace.vue";
import UnitBadge from "@/components/UnitBadge.vue";
import RarityBadge from "@/components/RarityBadge.vue";
import SkillBound from "@/components/SkillBound.vue";
import SkillDescription from "@/components/SkillDescription.vue";
import SourceBadge from "@/components/SourceBadge.vue";
import ElemIcon from "@/components/ElemIcon.vue";
import DropEquip from "@/pages/Worlds/DropEquip.vue";

import UnitSkillTable from "./UnitSkillTable.vue";
import UnitSkinView from "./UnitSkinView.vue";
import UnitDialogue from "./UnitDialogue.vue";
import UnitStats from "./UnitStats.vue";

import { RawSkin, SkinInfo, RawCostTable, Rarity } from "@/libs/Types";
import SkillData, { SkillEntity } from "@/libs/DB/Skill";

import { ACTOR_CLASS, ACTOR_GRADE, ROLE_TYPE } from "@/libs/Types/Enums";
import UnitData, { GetLinkBonus, LinkBonusType, Unit } from "@/libs/DB/Unit";
import EquipData from "@/libs/DB/Equip";
import UnitStatsData, { UnitStats as UnitStats_ } from "@/libs/DB/UnitStats";
import RequireResource from "@/libs/DB/RequireResource";

import { Unit as SimUnit } from "@/pages/Simulation/Simulation/Unit";

import SkinData from "@/json/unit-skin.json";
import CostData from "@/json/unit-cost.json";
import { GetRequireResource, UpdateTitle } from "@/libs/Functions";
import { SetMeta } from "@/libs/Meta";
import { AssetsRoot, ImageExtension } from "@/libs/Const";

interface SkillItem extends SkillEntity {
	index: number;
	isPassive: boolean;
}
type SkillTable = Record<string, SkillItem>;
interface VoiceItem extends SkinInfo {
	id: number;
	isDef: boolean;
	isPro: boolean;
	isMarry: boolean;
}

@Component({
	components: {
		NodeRenderer,
		UnitBadge,
		RarityBadge,
		UnitFace,
		ElemIcon,
		SkillBound,
		SkillDescription,
		SourceBadge,
		DropEquip,
		UnitSkillTable,
		UnitSkinView,
		UnitDialogue,
		UnitStats,
	},
})
export default class UnitView extends Vue {
	private rarityList: Record<ACTOR_GRADE, Rarity> = {
		[ACTOR_GRADE.B]: "B",
		[ACTOR_GRADE.A]: "A",
		[ACTOR_GRADE.S]: "S",
		[ACTOR_GRADE.SS]: "SS",
	};

	private costRarity: ACTOR_GRADE = ACTOR_GRADE.SS;

	private skinIndex: number = 0;

	private linkCount: number = 5;
	private formState: "normal" | "change" = "normal";

	private displayTab: "texts" | "information" | "dialogue" | "status" = "texts";

	private unitId: number = 0;
	private skillLevel: number = 0;

	private linkBonus: LinkBonusType = "";

	private statusSerialized: string | null = null;

	@Watch("$route")
	private routeChanged () {
		this.checkParams();
	}

	private GoBack () {
		this.$router.back();
	}

	private GoTo (path: string) {
		this.$router.push({ path });
	}

	private checkParams () {
		const params = this.$route.params;

		if ("stats" in params) {
			try {
				const _ = params.stats;
				const u = new SimUnit();
				const json = window.atob(_);

				u.Deserialize(json);
				localStorage.setItem(`unit-stats-${u.Id}`, json);
				u.$destroy();

				this.$router.replace(`/units/${u.Id}`);
				this.displayTab = "status";
			} catch (e) {
				// TODO : 올바르지 않은 공유 문자열 주소
			}
			return;
		} else if (!("id" in params)) {
			this.$router.replace("/units");
			return;
		}

		const id = params.id;
		if (/^[0-9]+$/.test(id)) {
			const iid = parseInt(params.id, 10);
			const unit = UnitData.find(x => x.id === iid);
			if (!unit)
				this.$router.replace("/units");
			else
				this.$router.replace("/units/" + unit.uid);
		} else {
			const unit = UnitData.find(x => x.uid === id);
			if (!unit) {
				this.$router.replace("/units");
				return;
			}
			this.unitId = unit.id;

			const typeName: Record<ACTOR_CLASS, string> = {
				[ACTOR_CLASS.LIGHT]: "경장",
				[ACTOR_CLASS.AIR]: "기동",
				[ACTOR_CLASS.HEAVY]: "중장",
				[ACTOR_CLASS.__MAX__]: "",
			};
			const roleName: Record<ROLE_TYPE, string> = {
				[ROLE_TYPE.ATTACKER]: "공격기",
				[ROLE_TYPE.DEFENDER]: "보호기",
				[ROLE_TYPE.SUPPORTER]: "지원기",
				[ROLE_TYPE.__MAX__]: "",
			};

			SetMeta(
				["description", "twitter:description"],
				`${this.RarityName[this.unit.rarity]}급 ${typeName[this.unit.type]} ${roleName[this.unit.role]} ${this.unit.name}의 정보입니다. ` +
				"기본 정보, 링크/풀링크 보너스, 스킬 정보, 대사를 확인할 수 있으며, 스테이터스 계산기를 이용할 수 있습니다.",
			);
			SetMeta(
				["twitter:image", "og:image"],
				`${AssetsRoot}/${ImageExtension()}/full/${("00" + this.unit.id).substr(-3)}.${ImageExtension()}`,
			);
			SetMeta("keywords", (this.unit.name === this.unit.shortname ? `,${this.unit.name}` : `,${this.unit.name},${this.unit.shortname}`), true);
			UpdateTitle("전투원정보", `${this.unit.name}`);
		}
	}

	private get unit () {
		return UnitData.find(x => x.id === this.unitId) || Unit.Empty;
	}

	private get RarityName () {
		return {
			[ACTOR_GRADE.B]: "B",
			[ACTOR_GRADE.A]: "A",
			[ACTOR_GRADE.S]: "S",
			[ACTOR_GRADE.SS]: "SS",
		};
	}

	private get LimitedEquip () {
		if (this.unit.hasLimited)
			return EquipData.find(x => x.fullKey === this.unit.hasLimited) || null;
		else
			return null;
	}

	private get LimitedEquipURL () {
		const unit = this.unit;
		if (!unit.hasLimited) return "";
		return `/equips/${unit.hasLimited}`;
	}

	private get LinkCountList () {
		return [0, 1, 2, 3, 4, 5].map(x => ({
			value: x,
			text: `${x} 링크`,
		}));
	}

	private get CurrentResists () {
		const stat = UnitStatsData.find(x => x.id === this.unit.id && x.rarity === this.costRarity);
		return (stat || UnitStats_.Empty).Resist;
	}

	private get LinkBonus () {
		return this.unit.linkBonus
			.filter(x => x)
			.map(x => GetLinkBonus(x, this.linkCount));
	}

	private get FullLinkBonus () {
		return this.unit.fullLinkBonus.map(x => GetLinkBonus(x, 1));
	}

	private get SkillPowerBonus () {
		let bonus = new Decimal(0);

		if (this.linkBonus === "Skill_2") bonus = bonus.add(2);
		if (this.linkBonus === "Skill_5") bonus = bonus.add(5);
		if (this.linkBonus === "Skill_10") bonus = bonus.add(10);
		if (this.linkBonus === "Skill_15") bonus = bonus.add(15);
		if (this.linkBonus === "Skill_20") bonus = bonus.add(20);
		if (this.linkBonus === "Skill_25") bonus = bonus.add(25);
		if (this.linkBonus === "Skill_30") bonus = bonus.add(30);
		if (this.linkBonus === "Skill_35") bonus = bonus.add(35);

		if (this.unit.linkBonus.includes("Skill_2")) bonus = bonus.add(Decimal.mul(2, this.linkCount));
		if (this.unit.linkBonus.includes("Skill_5")) bonus = bonus.add(Decimal.mul(5, this.linkCount));
		if (this.unit.linkBonus.includes("Skill_10")) bonus = bonus.add(Decimal.mul(10, this.linkCount));
		if (this.unit.linkBonus.includes("Skill_15")) bonus = bonus.add(Decimal.mul(15, this.linkCount));
		if (this.unit.linkBonus.includes("Skill_20")) bonus = bonus.add(Decimal.mul(20, this.linkCount));
		if (this.unit.linkBonus.includes("Skill_25")) bonus = bonus.add(Decimal.mul(25, this.linkCount));
		if (this.unit.linkBonus.includes("Skill_30")) bonus = bonus.add(Decimal.mul(30, this.linkCount));
		if (this.unit.linkBonus.includes("Skill_35")) bonus = bonus.add(Decimal.mul(35, this.linkCount));

		return bonus.toNumber();
	}

	private get CraftTime () {
		const duration = this.unit.craftable;
		if (!duration) return "-";

		const h = Math.floor(duration / 3600);
		const m = Math.floor(duration / 60) % 60;
		const s = duration % 60;
		return `${("0" + h).substr(-2)}:${("0" + m).substr(-2)}:${("0" + s).substr(-2)}`;
	}

	private get Favor () {
		return {
			clear: Decimal.mul(this.unit.favor.clear, 5)
				.floor()
				.div(100)
				.toNumber(),
			death: Decimal.mul(this.unit.favor.death, 2).toNumber(),
			assistant: Decimal.mul(this.unit.favor.assistant, 1).toNumber(),
		};
	}

	private get HasFormChange () {
		const raw = this.SkillsRaw;
		if (!raw) return false;

		return Object.keys(raw).some(x => x.startsWith("F"));
	}

	private get CostRarityList () {
		const list = [{
			value: this.unit.rarity,
			text: `${this.RarityName[this.unit.rarity]} 등급`,
		}];

		if (this.unit.promotions) {
			list.push(...this.unit.promotions.map(x => (
				{
					value: x,
					text: `${this.RarityName[x]} 승급`,
				}),
			));
		}

		return list;
	}

	private get Skin () {
		interface SkinTable {
			[key: string]: RawSkin;
		}

		if (this.unit.uid in SkinData)
			return (SkinData as unknown as SkinTable)[this.unit.uid];
		return null;
	}

	private get SkinList () {
		interface SkinItem extends SkinInfo {
			isDef: boolean;
			isPro: boolean;
		}

		const list: SkinItem[] = [];

		const skin = this.Skin;
		if (!skin) return list;

		// 캐릭터 기본 스킨
		list.push({
			...skin,
			t: this.unit.name,
			isDef: true,
			isPro: false,
			name: "",
			desc: "",
		});

		if (skin.skins) {
			list.push(...skin.skins.map((x, y) => {
				return {
					...x,
					isDef: false,
					isPro: false,
				};
			}));
		}

		if (skin.P) {
			list.push({
				...skin.P,
				isDef: false,
				isPro: true,
			});
		}

		this.Reset();
		return list;
	}

	private get VoiceList (): VoiceItem[] {
		return [
			{
				id: 0,
				...this.SkinList[0],
				isMarry: false,
			},
			...(this.unit.marry
				? [{
					id: 0,
					...this.SkinList[0],
					isMarry: true,
				}]
				: []),
			...this.SkinList
				.slice(1)
				.map((x, i) => ({
					id: i + 1,
					...x,
					isMarry: false,
				})),
		];
	}

	private get CostTable () {
		return GetRequireResource(
			this.costRarity,
			this.unit.type,
			this.unit.role,
			this.unit.body,
			this.linkBonus,
		);
	}

	/**
	 * 형태 전환 전/후를 모두 포함한 스킬 목록
	 */
	private get SkillsRaw () {
		const table = SkillData[this.unit.uid] as SkillTable;
		if (!table) return undefined;

		Object.keys(table)
			.forEach(x => {
				const y = /(passive|active)([0-9]+)/.exec(table[x].key);
				if (!y) return;

				table[x].index = parseInt(y[2], 10);
				table[x].isPassive = y[1].includes("passive");
			});
		return table;
	}

	/**
	 * 현재 선택 형태에 맞춘 스킬 목록
	 */
	private get Skills () {
		const output: SkillTable = {};
		const raw = this.SkillsRaw;
		if (!raw) return [];

		const keys = Object.keys(raw);
		return keys
			.filter(x => !x.startsWith("F"))
			.map(x => {
				const keyf = `F${x}`;
				if (this.formState === "change" && keys.includes(keyf))
					return raw[keyf];
				else
					return raw[x];
			});
	}

	private get SkillLevelList () {
		const ret = [];
		for (let i = 0; i < 13; i++)
			ret.push({ value: i, text: `Lv. ${i + 1}` });

		return ret;
	}

	private CostClass (level: number, value: number) {
		if (value === 0) return "text-secondary";
		if (this.linkBonus.startsWith("Cost_") && level === 5)
			return "text-primary";
		else
			return "";
	}

	private BonusSelectable (bonus: LinkBonusType) {
		const list: LinkBonusType[] = [
			"Cost_20", "Cost_25", "Cost_30", "Cost_35",
			"Buff_1", "Buff_2", "Buff_3",
			"Range_1",
			"Skill_2", "Skill_5", "Skill_10", "Skill_15", "Skill_20", "Skill_25", "Skill_30", "Skill_35",
		];
		return list.includes(bonus);
	}

	private Reset () {
		this.skinIndex = 0;
		this.skillLevel = 9;
		this.formState = "normal";
		this.costRarity = this.unit.rarity;
	}

	private mounted () {
		this.checkParams();
	}
}
</script>

<style lang="scss">
@function ratio($x, $y) {
	@return ($y / $x * 100) * 1%;
}

.unit-view {
	.tab-box {
		padding: 10px;
		border: 1px solid #dee2e6;
	}

	// .fulllink-table {
	//	padding-top: 0.55em;
	// }
	.introduce-text {
		word-break: keep-all;
		white-space: pre-line;
	}

	.table-unit-modal.container {
		.col {
			margin-bottom: -1px;
			padding: 0.75rem;
			border: 1px solid #dee2e6;
			&.bg-dark {
				border-color: #454d55;
				font-weight: bold;
			}
		}
	}
	.table-unit-modal.table-bordered {
		td,
		th {
			vertical-align: middle;
			word-break: keep-all;
		}
		th.table-dark {
			border-color: #454d55;
		}

		.rarity-badge {
			border: 1px solid rgba(0, 0, 0, 0.33);
			box-shadow: 0 0 1px #000;
		}
	}

	.table-unit-link-select {
		margin-left: 5px;
		width: 96px;
		vertical-align: baseline;
	}
	.table-unit-level-select,
	.table-unit-rarity-select {
		margin-left: 5px;
		width: 96px;
		vertical-align: baseline;
	}

	.skill-icon {
		height: 64px;
	}
	.unit-modal-skill {
		padding: 3px 0;
		border-bottom: 1px solid #dee2e6;

		&:last-child {
			border-bottom: 0;
		}
		&:empty {
			display: none;
		}
	}

	.drop-list {
		line-height: 1;
		a {
			display: inline-block;
			line-height: 1;
		}
	}

	.limited-item-card {
		display: inline-block;
		width: 100%;
		max-width: 20rem;
	}
}

.break-keep {
	word-break: keep-all;
}
</style>
