// src/components/drop-equip/index.tsx
import { Fragment, FunctionalComponent, h } from "preact";

import { FilterableEquip } from "@/types/DB/Equip.Filterable";

import { RarityDisplay } from "@/libs/Const";

import Locale from "@/components/locale";
import EquipIcon from "@/components/equip-icon";

import "./style.scss";

interface DropEquipProps {
	equip: FilterableEquip;
	chance?: number;
}

const DropEquip: FunctionalComponent<DropEquipProps> = (props) => {
	const chance = props.chance || 100;

	return <div class="drop-equip p-2 text-dark">
		<div class={ `card rarity-${RarityDisplay[props.equip.rarity]}` }>
			<div class="card-body">
				<EquipIcon class="float-left me-2" image={ props.equip.icon } />
				<div class="text-left">
					<span class="badge bg-secondary me-1">{ RarityDisplay[props.equip.rarity] }</span>
					<Locale k={ `EQUIP_${props.equip.fullKey}` } />
					{ chance < 100
						? <small class="ps-1 text-bold">({ chance }%)</small>
						: <Fragment />
					}
				</div>
			</div>
		</div>
	</div>;
};
export default DropEquip;

// src/pages/Worlds/DropEquip.vue
<template>
	<div class="drop-equip p-2 text-dark">
		<b-card :class="`rarity-${RarityDisplay[equip.rarity]}`">
			<equip-icon class="float-left mr-2" :image="equip.icon" />
			<div class="text-left">
				<b-badge variant="secondary" class="mr-1">{{ RarityDisplay[equip.rarity] }}</b-badge>
				<locale :k="`EQUIP_${equip.fullKey}`" />
				<small v-if="chance < 100" class="pl-1 text-bold">({{ chance }}%)</small>
			</div>
		</b-card>
	</div>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import { Watch, Prop } from "vue-property-decorator";

import EquipIcon from "@/components/EquipIcon.vue";

import { RarityDisplay } from "@/libs/Const";
import { ACTOR_GRADE } from "@/libs/Types/Enums";

import { FilterableEquip } from "@/libs/Types/Equip.Filterable";

@Component({
	components: {
		EquipIcon,
	},
})
export default class DropEquip extends Vue {
	@Prop({
		type: Object,
		required: true,
	})
	private equip!: FilterableEquip;

	@Prop({
		type: Number,
		default: 100,
	})
	private chance!: number;

	private get RarityDisplay () {
		return RarityDisplay;
	}
}
</script>

<style lang="scss">
.drop-equip {
	word-break: keep-all;
	user-select: none;
	cursor: pointer;

	.equip-icon {
		background-color: transparentize(#000, 0.8);
		box-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
	}
}
</style>
