// src/routes/worlds/components/world-item/index.tsx
import { Fragment, FunctionalComponent, h } from "preact";
import { Link } from "preact-router";

import { AssetsRoot } from "@/libs/Const";
import Locale from "@/components/locale";

interface WorldItemProps {
	wid: string;
	linked?: boolean;
}

import "./style.scss";

const WorldItem: FunctionalComponent<WorldItemProps> = (props) => {
	const WorldIcon = props.wid === "Cha" ? "Cha_0" : `${props.wid}_1`;

	return <div class="card world-item mb-4 bg-dark text-light">
		<div class="card-body">
			<div class="row text-left">
				<div class="col-auto">
					<img src={ `${AssetsRoot}/world/icons/${WorldIcon}.png` } />
				</div>
				<div class="col">
					<div class="world-item-name">
						<Locale k={ `WORLD_${props.wid}` } />
					</div>
					<hr class="my-1" />
					<div class="world-item-desc">
						<Locale k={ `WORLD_DESC_${props.wid}` } fallback="" />
					</div>
				</div>
			</div>
		</div>
		{ props.linked
			? props.wid === "Sub"
				? <Link href="/worlds/Sub/1/" class="stretched-link" />
				: <Link href={ `/worlds/${props.wid}` } class="stretched-link" />
			: <Fragment />
		}
	</div>;
};
export default WorldItem;

// src/pages/Worlds/WorldItem.vue
<template>
	<b-card class="world-item mb-4" text-variant="light" bg-variant="dark">
		<b-row class="text-left">
			<b-col cols="auto">
				<img :src="`${AssetsRoot}/world/icons/${WorldIcon}.png`" />
			</b-col>
			<b-col>
				<div class="world-item-name">{{ Name }}</div>
				<hr class="my-1" />
				<div class="world-item-desc">{{ Description }}</div>
			</b-col>
		</b-row>
		<a v-if="linked" :href="`/worlds/${wid}`" class="stretched-link" @click.prevent="Click" />
	</b-card>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import { Emit, Prop } from "vue-property-decorator";
import { LocaleGet } from "@/libs/Locale";

import { AssetsRoot } from "@/libs/Const";

@Component({})
export default class WorldItem extends Vue {
	@Prop({
		type: String,
		required: true,
	})
	private wid!: string;

	@Prop({
		type: Boolean,
		default: false,
	})
	private linked!: boolean;

	private get AssetsRoot () {
		return AssetsRoot;
	}

	private get Name () {
		return LocaleGet(`WORLD_${this.wid}`);
	}

	private get Description () {
		return LocaleGet([`WORLD_DESC_${this.wid}`, ""]);
	}

	private get WorldIcon () {
		if (this.wid === "Cha")
			return "Cha_0";
		else
			return `${this.wid}_1`;
	}

	private Click () {
		this.$emit("goto", `/worlds/${this.wid}`);
	}
}
</script>

<style lang="scss">
.world-item {
	.card-body {
		img {
			width: 100%;
			max-width: 6rem;
		}

		.world-item-name {
			font-size: 1.25rem;
		}
		.world-item-desc {
			word-break: keep-all;
			font-size: 0.875rem;
			opacity: 0.875;
		}
		hr {
			border-top-color: rgba(255, 255, 255, 0.1);
		}
	}
}
</style>
