// src/pages/Equips/EquipCard.vue
<template>
	<b-card bg-variant="dark" text-variant="white" class="my-1 equip-card" no-body>
		<b-card-header class="position-relative">
			<equip-icon :image="`${equip.icon}`" size="big" />
			<div v-if="Sources.length > 0" class="equip-sources text-left">
				<source-badge
					v-for="(source, sindex) in Sources"
					:key="`equip-${equip.fullKey}-source-${sindex}-${source.source}`"
					class="mb-1"
					:source="source"
					minimum
				/>
			</div>
		</b-card-header>

		<b-card-body>
			<div class="equip-name">{{ Name }}</div>
		</b-card-body>

		<a v-if="!noLink" href="#" class="stretched-link equip-stretched" @click.prevent="Click" />
	</b-card>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import { Emit, Prop } from "vue-property-decorator";
import { LocaleGet } from "@/libs/Locale";

import { FilterableEquip } from "@/libs/Types/Equip.Filterable";
import EntitySource from "@/libs/EntitySource";

import EquipIcon from "@/components/EquipIcon.vue";
import SourceBadge from "@/components/SourceBadge.vue";

@Component({
	components: {
		EquipIcon,
		SourceBadge,
	},
})
export default class EquipCard extends Vue {
	@Prop({
		type: Object,
		required: true,
	})
	private equip!: FilterableEquip;

	@Prop({
		type: Array,
		default: () => [],
	})
	private source!: EntitySource[];

	@Prop({
		type: Boolean,
		default: false,
	})
	private noLink!: boolean;

	private get Name () {
		return LocaleGet(`EQUIP_${this.equip.fullKey}`) // this.equip.name
			.replace(/ (RE|MP|SP|EX)$/, "");
	}

	private get Sources () {
		return this.source.reduce((p, c) => [...p, c], [] as EntitySource[]);
	}

	@Emit("click")
	private Click () {
		return this.equip.fullKey;
	}
}
</script>

<style lang="scss">
.equip-card {
	.equip-sources {
		position: absolute;
		margin-left: -0.25em;
		left: 4px;
		top: 4px;
		line-height: 0;

		> .equip-source {
			box-shadow: 0 0 4px #000;
		}
	}

	.card-body {
		padding: 0.5em;
	}

	.equip-name {
		word-break: keep-all;
	}
	.equip-stretched {
		margin: 0;
		padding: 0;
		width: 1px;
		height: 1px;
		overflow: hidden;
	}
}
</style>

// src/components/equip-card/index.tsx
import { Fragment, FunctionalComponent, h } from "preact";

import { FilterableEquip } from "@/types/DB/Equip.Filterable";

import EntitySource from "@/libs/EntitySource";

import EquipIcon from "@/components/equip-icon";
import { LocaleGet } from "@/components/locale";
import SourceBadge from "@/components/source-badge";

import "./style.scss";

interface EquipCardProps {
	class?: string;
	equip: FilterableEquip;
	source?: EntitySource[];
	noLink?: boolean;
}

const EquipCard: FunctionalComponent<EquipCardProps> = (props) => {
	const equip = props.equip;

	const Name = LocaleGet(`EQUIP_${equip.fullKey}`)
		.replace(/ (RE|MP|SP|EX)$/, "");

	const Sources = (props.source || [])
		.reduce((p, c) => [...p, c], [] as EntitySource[]);

	return <div class={ `card my-1 equip-card bg-dark text-light ${props.class || ""}` }>
		<div class="card-header position-relative">
			<EquipIcon image={ equip.icon } size="big" />
			{ Sources.length > 0
				? <div class="equip-sources text-left">
					{ Sources.map(source => <SourceBadge class="mb-1" source={ source } minimum />) }
				</div>
				: <Fragment /> }
		</div>
		<div class="card-body">
			<div class="equip-name">{ Name }</div>
		</div>
	</div>;
};
export default EquipCard;
