// src/pages/Units/UnitCard.vue
<template>
	<b-card v-if="!horizontal" class="unit-card position-relative my-1" bg-variant="dark" text-variant="white" :img-src="UnitFaceUrl">
		<div v-if="unit.name" class="unit-role-icon">
			<img :src="`${AssetsRoot}/icons/CHA_${RoleIconId}${RarityDisplay[unit.rarity]}.png`" />
		</div>

		<b-card-title>
			<div class="unit-info">
				<rarity-badge :rarity="unit.rarity" />
				<span>
					<span class="d-inline-block">No. {{ IdDisplay }}</span>
					<span class="d-inline-block">
						<i class="unit-type" :data-type="unit.type" />
						<!-- <i class="unit-role" :data-role="unit.role" /> -->
					</span>
				</span>
			</div>
			{{ unit.name }}

			<div class="unit-badges">
				<b-badge v-if="unit.body === 1" variant="info" class="ml-1">AGS</b-badge>
				<template v-if="leftPromotions">
					<rarity-badge v-for="pro in leftPromotions" :key="`unit-table-unit-${unit.uid}-pro-${pro}`" class="ml-1" :rarity="pro">
						{{ RarityDisplay[pro] }} 승급
					</rarity-badge>
				</template>
			</div>
		</b-card-title>

		<a v-if="!noLink" href="#" class="stretched-link unit-stretched" @click.prevent="OnClick()" />
	</b-card>
	<div v-else class="unit-card text-left clearfix" @click.prevent="!noLink && OnClick()">
		<unit-face :uid="unit.uid" class="unit-face float-left" />
		<div class="unit-name">{{ unit.name }}</div>
		<div class="unit-flag">
			<b-badge v-if="unit.body === 1" variant="info" class="mr-1">AGS</b-badge>
			<b-badge v-if="isPromoted" variant="danger" class="mr-1">승급 후</b-badge>

			<div v-if="leftPromotions" class="float-right">
				<rarity-badge v-for="pro in leftPromotions" :key="`unit-table-unit-${unit.uid}-pro-${pro}`" :rarity="pro" class="ml-1">
					{{ RarityDisplay[pro] }} 승급
				</rarity-badge>
			</div>
		</div>
	</div>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";

import UnitFace from "@/components/UnitFace.vue";
import RarityBadge from "@/components/RarityBadge.vue";
import { Prop, Emit } from "vue-property-decorator";

import { FilterableUnit } from "@/libs/Types/Unit.Filterable";
import { ACTOR_GRADE, ROLE_TYPE } from "@/libs/Types/Enums";
import { AssetsRoot, RarityDisplay } from "@/libs/Const";

@Component({
	components: {
		UnitFace,
		RarityBadge,
	},
})
export default class UnitCard extends Vue {
	@Prop({
		type: Object,
		required: true,
	})
	private unit!: FilterableUnit;

	@Prop({
		type: Boolean,
		default: false,
	})
	private horizontal!: boolean;

	@Prop({
		type: Number,
		default: ACTOR_GRADE.B,
	})
	private rarity!: ACTOR_GRADE;

	@Prop({
		type: Boolean,
		default: false,
	})
	private noLink!: boolean;

	private get AssetsRoot () {
		return AssetsRoot;
	}

	private get RoleIconId () {
		switch (this.unit.role) {
			case ROLE_TYPE.ATTACKER: return "Sword";
			case ROLE_TYPE.DEFENDER: return "Shield";
			case ROLE_TYPE.SUPPORTER: return "Gear";
		}
		return "";
	}

	private get IdDisplay () {
		return ("00" + this.unit.no).substr(-3);
	}

	private get UnitFaceUrl () {
		return UnitFace.GetURL(this.unit.uid);
	}

	private get RarityDisplay () {
		return RarityDisplay;
	}

	private get isPromoted () {
		return (this.unit.promo || []).includes(this.rarity);
	}

	private get leftPromotions () {
		return (this.unit.promo || []).filter(x => x > this.rarity);
	}

	@Emit("click")
	private OnClick () {
		return undefined;
	}
}
</script>

<style lang="scss">
.unit-card {
	position: relative;
	cursor: pointer;

	&.card {
		border-radius: 9px;

		.card-img-top {
			position: relative;

			.unit-face {
				width: 100%;
			}
			.card-img-badge {
				position: absolute;
				left: 4px;
				bottom: 4px;

				> .unit-badge {
					box-shadow: 0 0 4px #000;
				}
			}
		}
		.card-body {
			padding: 1em 0;

			.card-title {
				position: relative;
				margin: 0;
				font-size: 14px;
				word-break: keep-all;
			}

			.unit-info {
				font-size: 85%;

				> .rarity-badge {
					font-size: 100%;
				}
				> span:not(.badge) {
					opacity: 0.72;

					i {
						$basis: 18px;
						display: inline-block;
						width: $basis;
						height: $basis;
						margin-left: 4px;
						background-size: ($basis * 3) ($basis * 2);
						background-position: 0 0;
						background-repeat: no-repeat;
						vertical-align: bottom;

						&[data-type] {
							background-image: url($assetsRoot + "unit-type.png");
							&[data-type="0"] {
								background-position-x: 0px;
							}
							&[data-type="2"] {
								background-position-x: -$basis;
							}
							&[data-type="1"] {
								background-position-x: -($basis * 2);
							}
						}
						&[data-role] {
							background-image: url($assetsRoot + "unit-role.png");
							&[data-role="1"] {
								background-position-x: 0px;
							}
							&[data-role="0"] {
								background-position-x: -$basis;
							}
							&[data-role="2"] {
								background-position-x: -($basis * 2);
							}
						}
					}
				}
			}
		}

		.unit-role-icon {
			position: absolute;
			left: -1em;
			top: -2em;
			pointer-events: none;

			> img {
				width: 6em;
				height: 6em;
			}
		}

		.unit-badges {
			position: absolute;
			top: -2.5em;
			right: 0.125em;
			line-height: 0;
			font-size: 16px;

			> .badge {
				box-shadow: 0 0 4px #000;

				&:not(.badge-info) {
					color: #000;
				}
			}
		}
	}
}
</style>

// src/components/unit-card/index.tsx
import { Fragment, FunctionalComponent, h } from "preact";
import { Link } from "preact-router";

import { FilterableUnit } from "@/types/DB/Unit.Filterable";
import { ACTOR_BODY_TYPE, ACTOR_GRADE, ROLE_TYPE } from "@/types/Enums";

import { AssetsRoot, RarityDisplay } from "@/libs/Const";

import Locale, { LocaleGet } from "@/components/locale";
import UnitFace, { GetUnitFaceURL } from "@/components/unit-face";
import RarityBadge from "@/components/rarity-badge";

import "./style.scss";

interface UnitCardProps {
	class?: string;
	unit: FilterableUnit;
	noLink?: boolean;
	rarity?: ACTOR_GRADE;

	shortName?: boolean;

	onClick?: (e: Event) => void;
}

const Card: FunctionalComponent<UnitCardProps> = (props) => {
	const unit = props.unit;
	const rarity = props.rarity || ACTOR_GRADE.B;

	const RoleIconId = ({
		[ROLE_TYPE.ATTACKER]: "Sword",
		[ROLE_TYPE.DEFENDER]: "Shield",
		[ROLE_TYPE.SUPPORTER]: "Gear",
	})[unit.role];

	const IdDisplay = `00${unit.id}`.substr(-3);
	const UnitFaceUrl = GetUnitFaceURL(unit.uid);
	const unitName = ((): preact.VNode | preact.VNode[] => {
		if (props.shortName) {
			const name = LocaleGet(`UNIT_${unit.uid}`);
			const sname = LocaleGet(`UNIT_SHORT_${unit.uid}`);

			if (name === sname)
				return <Fragment>{ name }</Fragment>;

			return name
				.split(sname)
				.map(x => x.length === 0 ? <Fragment>{ sname }</Fragment> : <span class="text-secondary">{ x }</span>);
		}
		return <Locale k={ `UNIT_${unit.uid}` } />;
	})();

	const leftPromotions = (unit.promo || []).filter(x => x > rarity);

	return <div class="card unit-card position-relative my-1 bg-dark text-light">
		<img class="card-img-top" src={ UnitFaceUrl } alt="" />
		<div class="card-body">
			{ unit.id > 0
				? <div class="unit-role-icon">
					<img src={ `${AssetsRoot}/icons/CHA_${RoleIconId}${RarityDisplay[unit.rarity]}.png` } />
				</div>
				: <Fragment />
			}

			<h4 class="card-title">

				<div class="unit-info">
					<RarityBadge rarity={ unit.rarity } />
					<span>
						<span class="d-inline-block">No. { IdDisplay }</span>
						<span class="d-inline-block">
							<i class="unit-type" data-type={ unit.type } />
						</span>
					</span>
				</div>
				{ unitName }

				<div class="unit-badges">
					{ unit.body === 1
						? <span class="badge bg-info ms-1"><Locale k="COMMON_UNIT_BODY_AGS" /></span>
						: <Fragment />
					}

					{ leftPromotions
						? leftPromotions.map(pro => <RarityBadge class="ms-1" rarity={ pro }>
							<Locale k="UNIT_CARD_PROMOTION_BADGE" p={ [RarityDisplay[pro]] } />
						</RarityBadge>)
						: <Fragment />
					}
				</div>
			</h4>
			{ !props.noLink
				? <Link class="stretched-link unit-stretched" href={ `/units/${unit.uid}` } />
				: <Fragment />
			}
		</div>
	</div>;
};

const Horizontal: FunctionalComponent<UnitCardProps> = (props) => {
	const rarity = props.rarity || ACTOR_GRADE.B;
	const isPromoted = (props.unit.promo || []).includes(rarity);
	const leftPromotions = (props.unit.promo || []).filter(x => x > rarity);

	return <div class={ `unit-card text-left clearfix ${props.class || ""}` } onClick={ props.onClick }>
		<UnitFace uid={ props.unit.uid } class="float-left" />

		<div class="unit-name">
			<Locale k={ `UNIT_${props.unit.uid}` } />
		</div>

		<div class="unit-flag">
			{ props.unit.body === ACTOR_BODY_TYPE.AGS
				? <span class="badge bg-info me-1">
					<Locale k="COMMON_UNIT_BODY_AGS" />
				</span>
				: <Fragment />
			}
			{ isPromoted
				? <span class="badge bg-danger me-1">
					<Locale k="UNIT_CARD_PROMOTION_AFTER" />
				</span>
				: <Fragment />
			}

			{ leftPromotions
				? <div class="float-right">
					{ leftPromotions.map(pro => <RarityBadge rarity={ pro } class="ms-1">
						<Locale k="UNIT_CARD_PROMOTION_BADGE" p={ [RarityDisplay[pro]] } />
					</RarityBadge>) }
				</div>
				: <Fragment />
			}
		</div>
	</div>;
};

const UnitCard = {
	Card,
	Horizontal,
};
export default UnitCard;
