// src/pages/Units/SummonBadge.vue
<template>
	<div class="summon-badge" v-if="Summon">
		<b-badge variant="dark" class="summon-badge">
			"{{ Summon.name }}" 소환 / 최대 {{ Summon.overlap }}체 소환 가능 / {{ Summon.lifecycle }} 라운드 지속 🔗
			<a href="#" class="stretched-link" @click.prevent="display = true" />
		</b-badge>
		<b-modal v-model="display" size="lg" centered hide-footer content-class="summon-modal">
			<template #modal-title>
				<div class="text-left">
					{{ Summon.name }}
					<div style="font-size: 60%">{{ Summon.id }}</div>
				</div>
			</template>

			<b-container class="table-summon-modal mb-3">
				<b-row cols="1" cols-md="2">
					<b-col class="icon-container">
						<div class="position-relative d-inline-block">
							<div class="summon-icon">
								<img :src="`${AssetsRoot}/${imageExt}/tbar/${Summon.icon}.${imageExt}`" />
							</div>
						</div>
					</b-col>
					<b-col class="nested">
						<b-row cols="2">
							<b-col class="bg-dark text-white">유형</b-col>
							<b-col>
								<unit-badge :type="Summon.type" size="large" transparent black />
							</b-col>
							<b-col class="bg-dark text-white">역할</b-col>
							<b-col>
								<unit-badge :role="Summon.role" size="large" transparent black />
							</b-col>
							<div>
								<b-col class="bg-dark text-white">등급</b-col>
							</div>
							<b-col>
								<rarity-badge :rarity="Summon.rarity" />
							</b-col>
						</b-row>
					</b-col>
				</b-row>
			</b-container>

			<b-table-simple bordered fixed table-class="mt-2 text-center">
				<b-tbody>
					<b-tr>
						<b-td variant="dark">
							<b-input-group>
								<b-input-group-prepend>
									<b-button variant="secondary" @click="currentLevel = 1">
										<b-icon-chevron-double-down />
									</b-button>
									<b-button variant="secondary" @click="() => (currentLevel = Math.max(currentLevel - 1, 1))">
										<b-icon-chevron-down />
									</b-button>
									<div class="input-prepend">Lv.</div>
								</b-input-group-prepend>
								<b-input class="pl-5" v-model="currentLevel" number />
								<b-input-group-append>
									<b-button variant="secondary" @click="() => (currentLevel = Math.min(currentLevel + 1, 100))">
										<b-icon-chevron-up />
									</b-button>
									<b-button variant="secondary" @click="currentLevel = 100">
										<b-icon-chevron-double-up />
									</b-button>
								</b-input-group-append>
							</b-input-group>
						</b-td>
					</b-tr>
					<b-tr>
						<b-td class="bg-dark status-col p-0">
							<b-table-simple borderless table-class="mb-0">
								<b-tbody>
									<b-tr class="text-center text-white resist-parent">
										<b-td data-type="fire">
											<elem-icon inline elem="fire" />
											<strong class="pl-1">{{ Summon.res.fire }}%</strong>
										</b-td>
										<b-td data-type="ice">
											<elem-icon inline elem="ice" />
											<strong class="pl-1">{{ Summon.res.chill }}%</strong>
										</b-td>
										<b-td data-type="lightning">
											<elem-icon inline elem="lightning" />
											<strong class="pl-1">{{ Summon.res.thunder }}%</strong>
										</b-td>
									</b-tr>
								</b-tbody>
							</b-table-simple>
							<b-table-simple borderless table-class="mb-0">
								<b-tbody>
									<b-tr>
										<b-td class="text-left">
											<stat-icon inline stat="HP" />
											<span class="status-col-head">HP</span>
										</b-td>
										<b-td>
											<div class="status-col-value">{{ StatValue(Summon.hp, true) }}</div>
										</b-td>
										<b-td class="text-left" />
										<b-td />
									</b-tr>

									<b-tr>
										<b-td class="text-left">
											<stat-icon inline stat="ATK" />
											<span class="status-col-head">공격력</span>
										</b-td>
										<b-td>
											<div class="status-col-value">{{ StatValue(Summon.atk) }}</div>
										</b-td>
										<b-td class="text-left">
											<stat-icon inline stat="ACC" />
											<span class="status-col-head">적중률</span>
										</b-td>
										<b-td>
											<div class="status-col-value">{{ Summon.acc }}%</div>
										</b-td>
									</b-tr>

									<b-tr>
										<b-td class="text-left">
											<stat-icon inline stat="Cri" />
											<span class="status-col-head">치명타</span>
										</b-td>
										<b-td>
											<div class="status-col-value">{{ Summon.cri }}%</div>
										</b-td>
										<b-td class="text-left">
											<stat-icon inline stat="DEF" />
											<span class="status-col-head">방어력</span>
										</b-td>
										<b-td>
											<div class="status-col-value">{{ StatValue(Summon.def) }}</div>
										</b-td>
									</b-tr>

									<b-tr>
										<b-td class="text-left">
											<stat-icon inline stat="EV" />
											<span class="status-col-head">회피율</span>
										</b-td>
										<b-td>
											<div class="status-col-value">{{ Summon.eva }}%</div>
										</b-td>
										<b-td class="text-left">
											<stat-icon inline stat="SPD" />
											<span class="status-col-head">행동력</span>
										</b-td>
										<b-td>
											<div class="status-col-value">{{ Summon.spd }}</div>
										</b-td>
									</b-tr>
								</b-tbody>
							</b-table-simple>
						</b-td>
					</b-tr>
				</b-tbody>
			</b-table-simple>

			<b-container>
				<b-row class="summon-display-tabs mt-1" cols="4" cols-md="7">
					<b-col
						v-for="(skill, idx) in Skills"
						:key="`summon-modal-skill-${idx}`"
						:class="['mt-1', displayTab === `skill${idx + 1}` ? 'border border-bottom-0' : 'border-bottom']"
					>
						<a href="#" @click.prevent="displayTab = `skill${idx + 1}`">
							<img
								v-if="skill"
								class="skill-icon my-2"
								:src="`${AssetsRoot}/${imageExt}/skill/${skill.icon}_${skill.passive ? 'passive' : 'active'}.${imageExt}`"
							/>
						</a>
					</b-col>
				</b-row>

				<template v-for="(skill, idx) in Skills">
					<b-row v-if="displayTab === `skill${idx + 1}` && skill" :key="`summon-modal-skill-${idx}`">
						<b-col class="border border-top-0 text-left p-3">
							<elem-icon :elem="skill.type" />
							<strong>{{ skill.name }}</strong>
							<small class="ml-1">Lv.1</small>

							<div class="float-md-right bg-dark ml-md-2 mt-2 mt-md-0 p-2 text-center">
								<skill-bound :target="skill.target" :buffs="skill.buff" :level="0" :passive="skill.passive" />
							</div>

							<div class="mt-3 skill-desc">
								<div>
									<elem-icon :elem="skill.buff.type" class="mr-1" />
									<b-badge v-if="skill.buff.dismiss_guard" variant="warning" class="mr-1">보호 무시</b-badge>
									<b-badge v-if="skill.buff.target_ground" variant="danger" class="mr-1" title="땅 찍기">그리드 지정</b-badge>
									<b-badge v-if="skill.buff.acc_bonus" variant="success" class="mr-1">
										적중 보정
										{{ (skill.buff.acc_bonus > 0 ? "+" : "") + skill.buff.acc_bonus }}%
									</b-badge>
								</div>
								<hr class="my-1" />

								<div class="break-keep white-pre-line">
									<skill-description :text="Description(skill)" :level="0" :rates="GetRates(skill)" />
								</div>
							</div>

							<div class="clearfix" />
							<hr />

							<buff-list v-if="BuffList[skill.key].length > 0" :list="BuffList[skill.key]" />
						</b-col>
					</b-row>
				</template>
			</b-container>
		</b-modal>
	</div>
</template>

<script lang="ts">
import { Decimal } from "decimal.js";

import Vue from "vue";
import Component from "vue-class-component";
import { Prop, Watch, PropSync } from "vue-property-decorator";

import { AssetsRoot, ImageExtension } from "@/libs/Const";
import { ArrayUnique, FormatNumber } from "@/libs/Functions";
import { BuffStat } from "@/libs/Buffs/Buffs";

import NodeRenderer from "@/components/NodeRenderer.vue";
import UnitBadge from "@/components/UnitBadge.vue";
import RarityBadge from "@/components/RarityBadge.vue";
import SourceBadge from "@/components/SourceBadge.vue";
import ElemIcon from "@/components/ElemIcon.vue";
import StatIcon from "@/components/StatIcon.vue";

import SkillBound from "@/components/SkillBound.vue";
import SkillDescription from "@/components/SkillDescription.vue";
import BuffList from "@/components/BuffList";

import { ACTOR_GRADE, ITEM_TYPE } from "@/libs/Types/Enums";

import { Summon, SummonSkill } from "@/libs/Types/Summon";
import { SkillSummonInfo } from "@/libs/Types/Skill";

import SummonDB from "@/libs/DB/Summon";

@Component({
	components: {
		NodeRenderer,
		UnitBadge,
		RarityBadge,
		SourceBadge,
		ElemIcon,
		StatIcon,

		SkillBound,
		SkillDescription,
		BuffList,
	},
})
export default class SummonBadge extends Vue {
	@Prop({
		type: Object,
	})
	private summon!: SkillSummonInfo | null | undefined;

	private currentLevel: number = 1;

	private display: boolean = false;

	private displayTab: string = "skill1";

	@Watch("displaySync")
	private WatchDisplay () {
		this.displayTab = "skill1";
	}

	private get AssetsRoot () {
		return AssetsRoot;
	}

	private get imageExt () {
		return ImageExtension();
	}

	private get Summon () {
		if (!this.summon) return undefined;

		const summon = this.summon;
		return SummonDB.find(x => x.id === summon.char);
	}

	private get FamilyList () {
		if (!this.Summon) return [];

		const summon = this.Summon;
		return SummonDB
			.filter(x => x.name === summon.name)
			.map((x, i) => ({
				value: x.id,
				text: `${x.name} ${i + 1}`,
			}));
	}

	private get Skills () {
		if (!this.Summon) return [];
		const list: Array<SummonSkill | undefined> = this.Summon.skills;
		while (list.length < 6) list.push(undefined);
		return list;
	}

	private get RarityDisplay () {
		return {
			[ACTOR_GRADE.B]: "B",
			[ACTOR_GRADE.A]: "A",
			[ACTOR_GRADE.S]: "S",
			[ACTOR_GRADE.SS]: "SS",
		};
	}

	private Description (skill: SummonSkill) {
		if (!this.Summon) return "";

		const v = Decimal.mul(
			this.StatValue(this.Summon.atk),
			skill.buff.rate,
		)
			.floor()
			.toNumber();

		let t = skill.desc.toString();
		t = t.replace(/\{0\}/g, `[@::${v}~0: (${skill.buff.rate}배)]`);
		return t;
	}

	private GetRates (skill: SummonSkill) {
		if (!this.Summon) return [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

		return new Array(10).fill(skill.buff.rate);
	}

	private StatValue (stat: [number, number], floorPer: boolean = false) {
		if (floorPer) {
			return Decimal.add(
				stat[0],
				Decimal.mul(
					Decimal.floor(stat[1]),
					this.currentLevel - 1,
				),
			)
				.floor()
				.toNumber();
		} else {
			return Decimal.add(
				stat[0],
				Decimal.mul(stat[1], this.currentLevel - 1),
			)
				.floor()
				.toNumber();
		}
	}

	private get BuffList () {
		const output: Record<string, BuffStat[]> = {};
		this.Skills.forEach(skill => {
			if (!skill) return null;

			const stat = skill.buff.buffs;
			output[skill.key] = stat;
		});

		return output;
	}
}
</script>

<style lang="scss">
.summon-badge {
	display: inline-block;

	> .badge {
		position: relative;
	}
}
.summon-modal {
	.unknown-status {
		user-select: none;
		cursor: pointer;
	}

	.info-tab-button svg {
		width: 100%;
		height: 100%;
		max-width: 56px;
		max-height: 56px;
	}
	.skill-icon {
		width: 100%;
		max-width: 56px;
	}

	.white-pre-line {
		white-space: pre-line;
	}

	.table-summon-modal.container {
		margin-bottom: 0 !important;

		.col {
			margin-bottom: -1px;
			padding: 0.75rem;
			border: 1px solid #dee2e6;

			&.icon-container {
				display: flex;
				justify-content: center;
				align-items: center;

				.summon-icon {
					display: inline-block;
					border-radius: 3px;
					vertical-align: middle;
					overflow: hidden;

					img {
						display: block;
						width: 128px;
						height: 128px;
					}
				}
			}

			&.bg-dark {
				border-color: #454d55;
				font-weight: bold;
			}
			&.nested {
				padding: 0;
				border: 0;

				> .row {
					margin: 0;
				}
			}
		}
	}

	.skill-desc .rarity-badge {
		border: 1px solid rgba(0, 0, 0, 0.33);
		box-shadow: 0 0 1px #000;
	}

	.resist-parent {
		[data-type="fire"] {
			color: $red;
		}
		[data-type="ice"] {
			color: lighten($cyan, 20%);
		}
		[data-type="lightning"] {
			color: $yellow;
		}
	}

	.input-prepend {
		position: absolute;
		margin-left: 7.75em;
		line-height: 2.75em;
		font-weight: bold;
		font-size: 90%;
		color: $secondary;
		z-index: 5;
	}

	.status-col {
		> table {
			margin: auto;
			width: auto;
		}

		.status-col-head,
		.status-col-value {
			line-height: 1.2em;
			font-weight: bold;
			text-align: left;
		}

		.status-col-head {
			margin-left: 0.25em;
			word-break: keep-all;
			color: $gray-500;
		}
		.status-col-value {
			color: $gray-400;
		}

		@include media-breakpoint-up("xs") {
			flex-direction: column;
			align-items: center;
			text-align: center;

			.status-col-icon {
				padding-right: 0;
			}
			.status-col-head {
				text-align: center;
			}
		}
		@include media-breakpoint-up("lg") {
			flex-direction: row;
			align-items: flex-start;
			text-align: left;

			.status-col-icon {
				padding-right: 0.5em;
			}
		}
	}
}
</style>

// src/routes/units/components/summon-badge/index.tsx
import { Fragment, FunctionalComponent, h } from "preact";
import Decimal from "decimal.js";

import { SkillEntity, SkillSummonInfo } from "@/types/DB/Skill";
import { Summon, SummonSkill } from "@/types/DB/Summon";
import { BuffStat } from "@/types/Buffs";

import { objState } from "@/libs/State";
import { AssetsRoot, ImageExtension } from "@/libs/Const";
import { UniqueID } from "@/libs/Functions";

import Loader, { GetJson } from "@/components/loader";
import Locale, { LocaleGet } from "@/components/locale";
import PopupBase from "@/components/popup/base";
import Icon from "@/components/bootstrap-icon";
import StatIcon from "@/components/stat-icon";
import UnitBadge from "@/components/unit-badge";
import RarityBadge from "@/components/rarity-badge";
import ElemIcon from "@/components/elem-icon";
import SkillBound from "@/components/skill-bound";
import SkillDescription from "@/components/skill-description/SkillDescription";
import BuffList from "@/components/buff-list";
import AIList from "@/components/ai-list";

import "./style.scss";

interface SummonBadgeProps {
	class?: string;
	summon: SkillSummonInfo | null;
}

const SummonBadge: FunctionalComponent<SummonBadgeProps> = (props) => {
	const summon = props.summon;
	if (!summon) return <Fragment />;

	const display = objState<boolean>(false);
	const displayTab = objState<string>("skill1");

	return <Loader json={ `summon/${summon.char}` } content={ ((): preact.VNode => {
		const Summon = GetJson<Summon>(`summon/${summon.char}`);
		if (!Summon) return <Fragment />;

		const uid = UniqueID("summon-badge-modal-");
		const imageExt = ImageExtension();

		const Skills = ((): Array<SummonSkill | undefined> => {
			const list: Array<SummonSkill | undefined> = Summon.skills;
			while (list.length < 5) list.push(undefined);
			return list;
		})();

		function StatValue (stat: [number, number]): number {
			return new Decimal(stat[0])
				.floor()
				.toNumber();
		}

		function Description (skill: SummonSkill): string {
			if (!Summon) return "";

			const v = Decimal.mul(
				StatValue(Summon.stat.atk),
				skill.buff.rate,
			)
				.floor()
				.toNumber();

			let t = skill.desc.toString();
			t = t.replace(/\{0\}/g, `[@::${v}~0: (${skill.buff.rate}배)]`);
			return t;
		}

		const GetRates = (skill: SummonSkill): number[] => new Array(10).fill(skill.buff.rate);

		const buffList = ((): Record<string, BuffStat[]> => {
			const output: Record<string, BuffStat[]> = {};
			Skills.forEach(skill => {
				if (!skill) return null;

				const stat = skill.buff.buffs;
				output[skill.key] = stat;
			});

			return output;
		})();

		return <div class={ `summon-badge ${props.class || ""}` }>
			<span class="badge bg-dark summon-badge" role="button" onClick={ (): void => display.set(true) }>
				<Locale k="UNIT_SKILL_SUMMON_BADGE" p={ [<Locale k={ Summon.uid } />] } />
				<Icon icon="dot" />
				<Locale k="UNIT_SKILL_SUMMON_MAXIMUM" p={ [Summon.overlap] } />
				<Icon icon="dot" />
				<Locale k="UNIT_SKILL_SUMMON_ROUNDS" p={ [Summon.lifecycle] } />
				<Icon icon="link-45deg" class="ms-1" />
			</span>

			<PopupBase class="summon-modal text-center" bodyClass="pb-0" display={ display.value } size="xl" header={
				<h4>
					<div class="text-start">
						<Locale k={ Summon.uid } />
						<div style="font-size: 60%">{ Summon.uid }</div>
					</div>
				</h4> }
			>
				<table class="table table-bordered table-fixed table-summon-modal mt-2 text-center">
					<tbody>
						<tr class="d-table-row d-lg-none">
							<td class="p-0">
								<div class="icon-container">
									<div class="summon-icon m-3">
										<img src={ `${AssetsRoot}/${imageExt}/tbar/${Summon.icon}.${imageExt}` } />
									</div>
									<div class="row row-cols-2">
										<div class="col bg-dark text-white"><Locale k="ENEMY_VIEW_TYPE" /></div>
										<div class="col">
											<UnitBadge type={ Summon.type } size="large" transparent black />
										</div>
										<div class="col bg-dark text-white"><Locale k="ENEMY_VIEW_ROLE" /></div>
										<div class="col">
											<UnitBadge role={ Summon.role } size="large" transparent black />
										</div>
										<div class="col bg-dark text-white"><Locale k="ENEMY_VIEW_GRADE" /></div>
										<div class="col">
											<RarityBadge rarity={ Summon.rarity } />
										</div>
									</div>
								</div>
							</td>
						</tr>
						<tr>
							<td rowSpan={ 2 } class="p-0 d-lg-table-cell d-none">
								<div class="icon-container">
									<div class="summon-icon m-3">
										<img src={ `${AssetsRoot}/${imageExt}/tbar/${Summon.icon}.${imageExt}` } />
									</div>
									<div class="row row-cols-2">
										<div class="col bg-dark text-white"><Locale k="ENEMY_VIEW_TYPE" /></div>
										<div class="col">
											<UnitBadge type={ Summon.type } size="large" transparent black />
										</div>
										<div class="col bg-dark text-white"><Locale k="ENEMY_VIEW_ROLE" /></div>
										<div class="col">
											<UnitBadge role={ Summon.role } size="large" transparent black />
										</div>
										<div class="col bg-dark text-white"><Locale k="ENEMY_VIEW_GRADE" /></div>
										<div class="col">
											<RarityBadge rarity={ Summon.rarity } />
										</div>
									</div>
								</div>
							</td>
							<td class="bg-dark text-light">
								<div class="input-group">
									<button class="btn btn-secondary" disabled>
										<Icon icon="chevron-double-down" />
									</button>
									<button class="btn btn-secondary" disabled>
										<Icon icon="chevron-down" />
									</button>

									<div class="flex-1">
										<div class="input-prepend">Lv.</div>
										<input class="form-control ps-5" value="1" disabled />
									</div>

									<button class="btn btn-secondary" disabled>
										<Icon icon="chevron-up" />
									</button>
									<button class="btn btn-secondary" disabled>
										<Icon icon="chevron-double-up" />
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="bg-dark status-col p-0">
								<table class="table table-borderless mb-0">
									<tbody>
										<tr class="text-center text-white resist-parent">
											<td data-type="fire">
												<ElemIcon inline elem="fire" />
												<strong class="ps-1">{ Summon.stat.res.fire }%</strong>
											</td>
											<td data-type="ice">
												<ElemIcon inline elem="ice" />
												<strong class="ps-1">{ Summon.stat.res.chill }%</strong>
											</td>
											<td data-type="lightning">
												<ElemIcon inline elem="lightning" />
												<strong class="ps-1">{ Summon.stat.res.thunder }%</strong>
											</td>
										</tr>
									</tbody>
								</table>
								<table class="table table-borderless mb-0">
									<tbody>
										<tr>
											<td class="text-start">
												<StatIcon inline stat="HP" />
												<span class="status-col-head"><Locale k="ENEMY_VIEW_STAT_HP" /></span>
											</td>
											<td>
												<div class="status-col-value">{ StatValue(Summon.stat.hp) }</div>
											</td>
											<td class="text-start" />
											<td />
										</tr>

										<tr>
											<td class="text-start">
												<StatIcon inline stat="ATK" />
												<span class="status-col-head"><Locale k="ENEMY_VIEW_STAT_ATK" /></span>
											</td>
											<td>
												<div class="status-col-value">{ StatValue(Summon.stat.atk) }</div>
											</td>
											<td class="text-start">
												<StatIcon inline stat="ACC" />
												<span class="status-col-head"><Locale k="ENEMY_VIEW_STAT_ACC" /></span>
											</td>
											<td>
												<div class="status-col-value">{ Summon.stat.acc }%</div>
											</td>
										</tr>

										<tr>
											<td class="text-start">
												<StatIcon inline stat="CRI" />
												<span class="status-col-head"><Locale k="ENEMY_VIEW_STAT_CRIT" /></span>
											</td>
											<td>
												<div class="status-col-value">{ Summon.stat.cri }%</div>
											</td>
											<td class="text-start">
												<StatIcon inline stat="DEF" />
												<span class="status-col-head"><Locale k="ENEMY_VIEW_STAT_DEF" /></span>
											</td>
											<td>
												<div class="status-col-value">{ StatValue(Summon.stat.def) }</div>
											</td>
										</tr>

										<tr>
											<td class="text-start">
												<StatIcon inline stat="EVA" />
												<span class="status-col-head"><Locale k="ENEMY_VIEW_STAT_EVA" /></span>
											</td>
											<td>
												<div class="status-col-value">{ Summon.stat.eva }%</div>
											</td>
											<td class="text-start">
												<StatIcon inline stat="SPD" />
												<span class="status-col-head"><Locale k="ENEMY_VIEW_STAT_SPD" /></span>
											</td>
											<td>
												<div class="status-col-value">{ Summon.stat.spd }</div>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>

				<div class="container mb-3">
					<div class="row row-cols-6 summon-display-tabs mt-1">
						{ Skills.map((skill, idx) => <div
							class={ [
								"col",
								"mt-1",
								displayTab.value === `skill${idx + 1}` ? "border border-bottom-0" : "border-bottom",
							].join(" ") }
							role="button"
							onClick={ (e): void => {
								e.preventDefault();
								displayTab.set(`skill${idx + 1}`);
							} }
						>
							{ skill
								? <img
									class="skill-icon my-2"
									src={ [
										AssetsRoot,
										imageExt,
										"skill",
										`${skill.icon}_${skill.passive ? "passive" : "active"}.${imageExt}`,
									].join("/") }
								/>
								: <Fragment />
							}
						</div>) }
						<div
							class={ `col mt-1 ${displayTab.value === "ai" ? "border border-bottom-0" : "border-bottom"}` }
							role="button"
							onClick={ (e): void => {
								e.preventDefault();
								displayTab.set("ai");
							} }
						>
							<Icon icon="cpu-fill" class="my-2" />
						</div>
					</div>

					{ Skills.map((skill, idx) => displayTab.value === `skill${idx + 1}` && skill
						? <div class="row">
							<div class="col border border-top-0 text-start p-3">
								<ElemIcon elem={ skill.type } />
								<strong>{ skill.name }</strong>
								<small class="ms-1">Lv.1</small>

								<div class="float-md-right bg-dark ms-md-2 mt-2 mt-md-0 p-2 text-center">
									<SkillBound
										target={ skill.target }
										buffs={ skill.buff }
										level={ 0 }
										passive={ skill.passive }
										rangeBonus={ false }
									/>
								</div>

								<div class="skill-desc">
									<div>
										<ElemIcon elem={ skill.buff.type } class="me-1" />

										{ skill.buff.dismiss_guard
											? <span class="badge bg-warning text-dark me-1">
												<Locale k="ENEMY_SKILL_DISMISS_GUARD" />
											</span>
											: <Fragment />
										}
										{ skill.buff.target_ground
											? <span class="badge bg-danger me-1" title={ LocaleGet("ENEMY_SKILL_GRID_TARGET_TIP") }>
												<Locale k="ENEMY_SKILL_GRID_TARGET" />
											</span>
											: <Fragment />
										}
										{ skill.buff.acc_bonus
											? <span class="badge bg-success me-1">
												<Locale k="ENEMY_SKILL_ACC_BONUS" />
												{ (skill.buff.acc_bonus > 0 ? "+" : "") + skill.buff.acc_bonus }%
												</span>
											: <Fragment />
										}
									</div>
									<hr class="my-1" />

									<div class="break-keep white-pre-line">
										<SkillDescription
											text={ Description(skill) }
											level={ 0 }
											rates={ GetRates(skill) }
											buffBonus={ false }
											favorBonus={ false }
											skillBonus={ 0 }
										/>
									</div>
								</div>

								<div class="clearfix" />
								<hr />

								{ buffList[skill.key].length > 0
									? <BuffList list={ buffList[skill.key] } />
									: <Fragment />
								}
							</div>
						</div>
						: <Fragment />) }

					{ displayTab.value === "ai"
						? <div class="row">
							<div class="col border border-top-0 text-start p-3">
								<AIList
									ai={ Summon.ai }
									skills={ Skills.filter(x => x) as unknown as SkillEntity[] }
									enemy={ false }
								/>
							</div>
						</div>
						: <Fragment />
					}
				</div>
			</PopupBase>
		</div>;
	}) } />;
};
export default SummonBadge;
