// src/pages/Worlds/DropUnit.vue
<template>
	<div class="drop-unit p-2 text-dark">
		<b-card v-if="unit" :class="`text-left rarity-${RarityDisplay[unit.rarity]}`">
			<unit-face class="float-left mr-2" :uid="unit.uid" size="48" type="mini" />
			<div>
				<b-badge variant="secondary" class="mr-1 bordered">{{ RarityDisplay[unit.rarity] }}</b-badge>
				<span class="unit-info">
					<i class="unit-type" :data-type="unit.type" />
					<i class="unit-role" :data-role="unit.role" />
				</span>
			</div>
			<div class="float-left">{{ unit.name }}</div>
			<small v-if="chance < 100" class="ml-1 text-bold">({{ chance }}%)</small>
		</b-card>
	</div>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import { Watch, Prop } from "vue-property-decorator";

import UnitFace from "@/components/UnitFace.vue";
import RarityBadge from "@/components/RarityBadge.vue";

import { ACTOR_GRADE } from "@/libs/Types/Enums";

import { FilterableUnit } from "@/libs/Types/Unit.Filterable";
import FilterableUnitDB from "@/libs/DB/Unit.Filterable";
import { RarityDisplay } from "@/libs/Const";

@Component({
	components: {
		UnitFace,
	},
})
export default class DropUnit extends Vue {
	@Prop({
		type: [String, Number],
		required: true,
	})
	private id!: number | string;

	@Prop({
		type: Number,
		default: 100,
	})
	private chance!: number;

	private get unit () {
		if (typeof this.id === "number")
			return FilterableUnitDB.find(x => x.no === this.id);
		else
			return FilterableUnitDB.find(x => x.uid === this.id);
	}

	private get RarityDisplay () {
		return RarityDisplay;
	}
}
</script>

<style lang="scss">
.drop-unit {
	user-select: none;
	cursor: pointer;

	.unit-face {
		box-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
	}
	span.unit-info {
		opacity: 0.72;

		i {
			$basis: 18px;
			display: inline-block;
			width: $basis;
			height: $basis;
			margin-right: 4px;
			background-size: ($basis * 3) ($basis * 2);
			background-position: 0 0;
			background-repeat: no-repeat;
			vertical-align: bottom;

			background-position-y: -$basis;

			&[data-type] {
				background-image: url($assetsRoot + "unit-type.png");
				&[data-type="light"] {
					background-position-x: 0px;
				}
				&[data-type="air"] {
					background-position-x: -$basis;
				}
				&[data-type="heavy"] {
					background-position-x: -($basis * 2);
				}
			}
			&[data-role] {
				background-image: url($assetsRoot + "unit-role.png");
				&[data-role="attacker"] {
					background-position-x: 0px;
				}
				&[data-role="defender"] {
					background-position-x: -$basis;
				}
				&[data-role="supporter"] {
					background-position-x: -($basis * 2);
				}
			}
		}
	}
}
</style>

// src/components/drop-unit/index.tsx
import { Fragment, FunctionalComponent, h } from "preact";

import { FilterableUnit } from "@/types/DB/Unit.Filterable";

import JsonLoader, { GetJson, StaticDB } from "@/libs/JsonLoader";
import { RarityDisplay } from "@/libs/Const";

import Locale from "@/components/locale";
import UnitFace from "@/components/unit-face";

import "./style.scss";

interface DropUnitProps {
	id: string | number;
	chance?: number;
}

const DropUnit: FunctionalComponent<DropUnitProps> = (props) => {
	const chance = props.chance || 100;

	return JsonLoader(
		StaticDB.FilterableUnit,
		() => {
			const FilterableUnitDB = GetJson<FilterableUnit[]>(StaticDB.FilterableUnit);

			const unit = typeof props.id === "number"
				? FilterableUnitDB.find(x => x.id === props.id)
				: FilterableUnitDB.find(x => x.uid === props.id);

			return <div class="drop-unit p-2 text-dark">
				{ unit
					? <div class={ `card text-left rarity-${RarityDisplay[unit.rarity]}` }>
						<div class="card-body">
							<UnitFace class="float-left me-2" uid={ unit.uid } size="48" type="mini" />
							<div>
								<span class="badge bg-secondary me-1 bordered">{ RarityDisplay[unit.rarity] }</span>
								<span class="unit-info">
									<i class="unit-type" data-type={ unit.type } />
									<i class="unit-role" data-role={ unit.role } />
								</span>
							</div>
							<div class="float-left">
								<Locale k={ `UNIT_${unit.uid}` } />
							</div>
							{ chance < 100
								? <small class="ms-1 text-bold">({ chance }%)</small>
								: <Fragment />
							}
						</div>
					</div>
					: <Fragment />
				}
			</div>;
		},
	);
};
export default DropUnit;
