// src/routes/worlds/index.tsx
import { FunctionalComponent, h } from "preact";

import { WorldIds } from "@/libs/Const";
import { SetMeta, UpdateTitle } from "@/libs/Site";

import Locale, { LocaleGet } from "@/components/locale";
import WorldItem from "@/routes/worlds/components/world-item";
import Icon from "@/components/bootstrap-icon";

const Worlds: FunctionalComponent = () => {
	const Tops = ["Story", "Ev5"];
	const Subs = ["Sub", "Cha"];
	const List = WorldIds.filter(x => !x.startsWith("EvA") && !Tops.includes(x) && !Subs.includes(x));

	SetMeta(["description", "twitter:description"], "세계 목록을 표시합니다. 현재 진행중이거나 진행될 예정인 이벤트도 확인할 수 있습니다.");
	SetMeta(["twitter:image", "og:image"], null);
	UpdateTitle(LocaleGet("MENU_WORLDS"));
	
	return <div class="worlds text-left">
		<h2>
			<Locale k="MENU_WORLDS" />
		</h2>
		<hr />

		<h4>
			<Locale k="WORLDS_MAINSTORY_EVENT" components={ { Icon } }  />
		</h4>
		<div class="row row-cols-1 row-cols-lg-2">
			{ Tops.map(item => <div class="col">
				<WorldItem linked wid={ item } />
			</div>) }
		</div>
		<hr />

		<h4>
			<Locale k="WORLDS_SUBSTORY_CHALLENGE" components={ { Icon } } />
		</h4>
		<div class="row row-cols-1 row-cols-lg-2">
			{ Subs.map(item => <div class="col">
				<WorldItem linked wid={ item } />
			</div>) }
		</div>
		<hr />

		<h4>
			<Locale k="WORLDS_PAST_EVENT" components={ { Icon } }  />
		</h4>
		<div class="row row-cols-1 row-cols-lg-2">
			{ List.map(item => <div class="col">
				<WorldItem linked wid={ item } />
			</div>) }
		</div>
	</div>;
};
export default Worlds;

// src/pages/Worlds.vue
<template>
	<div class="worlds text-left">
		<h2>
			<locale k="MENU_WORLDS" />
		</h2>
		<hr />

		<h4>
			<locale k="WORLDS_MAINSTORY_EVENT" />
		</h4>
		<b-row cols="1" cols-lg="2">
			<b-col v-for="item in Tops" :key="`worlds-top-${item}`">
				<world-item linked :wid="item" @goto="GoTo" />
			</b-col>
		</b-row>
		<hr />

		<h4>
			<locale k="WORLDS_SUBSTORY_CHALLENGE" />
		</h4>
		<b-row cols="1" cols-lg="2">
			<b-col v-for="item in SupCha" :key="`worlds-list-${item}`">
				<world-item linked :wid="item" @goto="GoTo" />
			</b-col>
		</b-row>
		<hr />

		<h4>
			<locale k="WORLDS_PAST_EVENT" />
		</h4>
		<b-row cols="1" cols-lg="2">
			<b-col v-for="item in List" :key="`worlds-list-${item}`">
				<world-item linked :wid="item" @goto="GoTo" />
			</b-col>
		</b-row>
	</div>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import { Watch } from "vue-property-decorator";
import { LocaleGet } from "@/libs/Locale";

import WorldItem from "./Worlds/WorldItem.vue";

import { AssetsRoot, ImageExtension, WorldIds } from "@/libs/Const";
import { UpdateTitle } from "@/libs/Functions";
import { SetMeta } from "@/libs/Meta";

@Component({
	components: {
		WorldItem,
	},
})
export default class Worlds extends Vue {
	private get AssetsRoot () {
		return AssetsRoot;
	}

	private get Tops () {
		return ["Story", "Ev10"];
	}

	private get SupCha () {
		return ["Sup1", "Cha"];
	}

	private get List () {
		return WorldIds
			.filter(x => !x.startsWith("EvA") &&
				!this.Tops.includes(x) &&
				!this.SupCha.includes(x));
	}

	private GoTo (path: string) {
		this.$router.push({ path });
	}

	private mounted () {
		SetMeta(["description", "twitter:description"], "세계 목록을 표시합니다. 현재 진행중이거나 진행될 예정인 이벤트도 확인할 수 있습니다.");
		SetMeta(["twitter:image", "og:image"], null);
		UpdateTitle(LocaleGet("MENU_WORLDS"));
	}
}
</script>

<style lang="scss">
/*
#app > .container > .worlds {
}
*/
</style>
