// src/components/rarity-badge/index.tsx
import { FunctionalComponent, h } from "preact";

import { ACTOR_GRADE } from "@/types/Enums";

import { RarityDisplay } from "@/libs/Const";

import style from "./style.scss";

interface RarityBadgeProps {
	class?: string;
	rarity: "B" | "A" | "S" | "SS" | ACTOR_GRADE;
	size?: "normal" | "medium" | "large";
	border?: boolean;
}

const RarityBadge: FunctionalComponent<RarityBadgeProps> = (props) => {
	const rarity = typeof props.rarity === "string"
		? props.rarity
		: RarityDisplay[props.rarity];

	const className = [
		"badge",
		"bg-light",
		"rarity-badge",
		props.border ? style["bordered"] : "",
		props.class || "",
		style["rarity-badge"],
		`rarity-${rarity}-force`,
	]
		.filter(x => x)
		.join(" ");

	return <span
		class={ className }
		data-rarity={ rarity }
		data-size={ props.size }
	>
		{ props.children || rarity }
	</span>;
};
export default RarityBadge;

// src/components/RarityBadge.vue
<script lang="tsx">
import Vue from "vue";
import Component from "vue-class-component";
import { Prop } from "vue-property-decorator";

import { Rarity } from "@/libs/Types";
import { ACTOR_GRADE } from "@/libs/Types/Enums";

const rarityTable: Record<ACTOR_GRADE, string> = {
	[ACTOR_GRADE.B]: "B",
	[ACTOR_GRADE.A]: "A",
	[ACTOR_GRADE.S]: "S",
	[ACTOR_GRADE.SS]: "SS",
};

@Component({})
export default class RarityBadge extends Vue {
	@Prop({
		type: [String, Number],
		required: true,
	})
	private rarity!: Rarity | ACTOR_GRADE;

	@Prop({
		type: String,
		default: "normal",
	})
	private size!: string;

	@Prop({
		type: Boolean,
		default: false,
	})
	private border!: boolean;

	private render () {
		const rarity = typeof this.rarity === "string"
			? this.rarity
			: rarityTable[this.rarity];

		return <b-badge variant="light" class={["rarity-badge", this.border ? "bordered" : ""]} data-rarity={rarity} data-size={this.size}>
			{this.$slots.default || rarity}
		</b-badge>;
	}
}
</script>

<style lang="scss">
.badge.rarity-badge {
	margin-right: 2px;
	font-size: 75%;
	color: #000;

	&.bordered {
		box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.25);
	}

	&:last-child {
		margin-right: 0 !important;
	}

	&[data-rarity="B"],
	&[data-rarity="b"] {
		background-color: #e2f0d9;
	}
	&[data-rarity="A"],
	&[data-rarity="a"] {
		background-color: #deebf7;
	}
	&[data-rarity="S"],
	&[data-rarity="s"] {
		background-color: #fff2cc;
	}
	&[data-rarity="SS"],
	&[data-rarity="ss"] {
		background-color: #fce391;
	}

	&[data-size="medium"] {
		margin-right: 6px;
		font-size: 100%;
	}
	&[data-size="large"] {
		margin-right: 10px;
		font-size: 120%;
	}
}
</style>
