// src/components/skill-bound/index.tsx
import { FunctionalComponent } from "preact";

import { SkillEntryData, SkillEntity } from "@/types/DB/Skill";

import { objState } from "@/libs/State";
import { groupBy, isActive } from "@/libs/Functions";

import Locale from "@/components/locale";

import "./style.scss";

interface BoundData {
	match: string;
	offset: number;
	global: boolean;
}

interface BoundListEntity {
	level: number;
	bound: BoundData;
}

interface SkillBoundProps {
	target: "team" | "enemy";
	buffs: SkillEntryData | SkillEntity["buffs"];
	level: number;
	passive: boolean;
	rangeBonus: boolean;
}

const SkillBound: FunctionalComponent<SkillBoundProps> = ({ target, buffs, level, passive, rangeBonus }) => {
	const Skill = "index" in buffs
		? buffs.data[buffs.index[level - 1]]
		: buffs;

	const AP = Skill.ap;
	const Range = Skill.range;

	function GetBound (skill: SkillEntryData): BoundData {
		let match = skill.grid;
		let offset = 5;
		let global = false;

		if (match === "single" || match === "self") {
			offset = 5;
			match = "5";
		} else if (match === "global") {
			offset = 5;
			match = "123456789";
			global = true;
		} else if (match === "fill") {
			offset = 5;
			match = "123456789";
		} else if (match === "around") {
			offset = 5;
			match = "12346789";
		} else if (match.includes(">")) {
			const from = match.substr(0, match.indexOf(">"));
			if (from === "F")
				global = true;
			else
				offset = parseInt(from, 10);

			match = match.substr(match.indexOf(">") + 1);
		}
		return { match, offset, global };
	}
	const BoundList = "index" in buffs
		? ((): BoundListEntity[] => {
			const indicies: number[] = [];
			const ret: BoundListEntity[] = [];
			for (let i = 0; i < 10; i++) {
				const idx = buffs.index[i];
				if (indicies.includes(idx)) continue;

				indicies.push(idx);
				ret.push({
					level: i,
					bound: GetBound(buffs.data[idx]),
				});
			}
			return ret.reduce((p, c) => {
				if (p.some(x => c.bound.global === x.bound.global &&
					c.bound.match === x.bound.match &&
					c.bound.offset === x.bound.offset)) return p;
				return [...p, c];
			}, [] as BoundListEntity[]);
		})()
		: [{
			level: 1,
			bound: GetBound(Skill),
		}];

	const prevLevel = objState<number>(level);

	const currentBoundLevel = objState<number>(BoundList.length - 1);
	const Bound = BoundList[Math.min(BoundList.length - 1, currentBoundLevel.value)].bound;

	if (prevLevel.value !== level) {
		prevLevel.set(level);

		for (let i = 0; i < BoundList.length; i++) {
			const item = BoundList[i];

			if (level >= item.level + 1)
				currentBoundLevel.set(i);
		}
	}

	const IsGlobal = Bound.global;

	const rangeBack = new Array(6)
		.fill(0)
		.map((_, i) => <span class="grid" data-pos={ i + 1 } />);

	const gridBack = new Array(9)
		.fill(0)
		.map((_, i) => <span class="grid" data-pos={ i + 1 } />);

	const rangeCells = new Array(Math.min(Range + (Range > 0 && rangeBonus ? 1 : 0), 6))
		.fill(0)
		.map((_, i) => <span class="range" data-pos={ i + 1 } />);

	const targets: preact.VNode[] = [];

	const t = Bound.match;
	const offset = Bound.offset;

	for (let i = 0; i < t.length; i++) {
		// @ 25%, # 50%, $ 75%
		// ^ value 50%, display 25%
		// & value 75%, display 50%
		const c = t[i];

		const cTable: Record<string, number> = {
			"@": 25,
			"#": 50,
			$: 75,
		};
		if (c in cTable)
			targets.push(<span class={ `target target-${cTable[c]} ${target}` } data-pos={ t[++i] } />);
		else
			targets.push(<span class={ `target ${target}` } data-pos={ c } />);
	}

	return <div class="skill-bound" data-passive={ passive ? 1 : 0 }>
		<div class="skill-range">
			{ rangeBack }
			{ rangeCells }
			{
				rangeBonus && Range > 0
					? <div class="skill-range-circle bonused">{ Range + 1 }</div>
					: <div class="skill-range-circle">{ Range }</div>
			}
		</div>

		<div class="skill-ap">
			<div class="me-1">AP</div>
			{ AP }
		</div>

		<div class="skill-grid">
			{ gridBack }
			{ IsGlobal
				? <></>
				: <span class="offset" data-pos={ offset } />
			}
			{ targets }
		</div>

		{ IsGlobal
			? <div class="global-text">
				<Locale k="UNIT_SKILL_BOUND_FIXED" />
			</div>
			: <></>
		}
		{ target === "team"
			? <div class="team-text">
				{ Skill.grid === "self"
					? <Locale k="UNIT_SKILL_BOUND_SELF" />
					: <Locale k="UNIT_SKILL_BOUND_TEAM" />
				}
			</div>
			: <></>
		}

		{ BoundList.length > 1
			? Object.values(groupBy(BoundList, (v, i) => Math.floor(i / 3)))
				.map(g => <div class="level-selector btn-group">
					{ g.map((x, i) => <button
						class={ `btn btn-sm btn-outline-light ${isActive(currentBoundLevel.value === i)}` }
						onClick={ (e): void => {
							e.preventDefault();
							e.stopPropagation();
							currentBoundLevel.set(i);
						} }
					>
						Lv.<strong>{ x.level + 1 }</strong>
					</button>) }
				</div>)
			: <></>
		}
	</div>;
};
export default SkillBound;

// src/components/SkillBound.vue
<script lang="tsx">
import { SkillEntity, SkillEntryData } from "@/libs/Types/Skill";

import Vue from "vue";
import Component from "vue-class-component";
import { Prop } from "vue-property-decorator";

@Component({})
export default class SkillBound extends Vue {
	@Prop({
		type: String,
		required: true,
	})
	private target!: "team" | "enemy";

	@Prop({
		type: [Object, Array],
		required: true,
	})
	private buffs!: SkillEntryData | SkillEntity["buffs"];

	@Prop({
		type: Number,
		default: 0,
	})
	private level!: number;

	@Prop({
		type: Boolean,
		default: false,
	})
	private passive!: boolean;

	@Prop({
		type: Boolean,
		default: false,
	})
	private rangeBonus!: boolean;

	private get IsGlobal () {
		return this.Bound.global;
	}

	private get Skill () {
		if ("index" in this.buffs)
			return this.buffs.data[this.buffs.index[this.level - 1]];
		else
			return this.buffs;
	}

	private get AP () {
		return this.Skill.ap;
	}

	private get Range () {
		return this.Skill.range;
	}

	private get Bound () {
		let match = this.Skill.grid;
		let offset = 5;
		let global = false;

		if (match === "single" || match === "self") {
			offset = 5;
			match = "5";
		} else if (match === "global") {
			offset = 5;
			match = "123456789";
			global = true;
		} else if (match === "fill") {
			offset = 5;
			match = "123456789";
		} else if (match === "around") {
			offset = 5;
			match = "12346789";
		} else if (match.includes(">")) {
			const from = match.substr(0, match.indexOf(">"));
			if (from === "F")
				global = true;
			else
				offset = parseInt(from, 10);

			match = match.substr(match.indexOf(">") + 1);
		}
		return { match, offset, global };
	}

	private get rangeBack () {
		const rangeGrid: JSX.Element[] = [];

		for (let i = 0; i < 6; i++)
			rangeGrid.push(<span class="grid" data-pos={ i + 1 } />);

		return rangeGrid;
	}

	private get gridBack () {
		const grids: JSX.Element[] = [];

		for (let i = 0; i < 9; i++)
			grids.push(<span class="grid" data-pos={ i + 1 } />);

		return grids;
	}

	private get rangeCells () {
		const ranges: JSX.Element[] = [];
		const range = Math.min(this.Range + (this.Range > 0 && this.rangeBonus ? 1 : 0), 6);

		for (let i = 0; i < range; i++)
			ranges.push(<span class="range" data-pos={ i + 1 } />);

		return ranges;
	}

	private render () {
		const targets: JSX.Element[] = [];

		const b = this.Bound;
		const t = b.match;
		const offset = b.offset;

		for (let i = 0; i < t.length; i++) {
			// @ 25%, # 50%, $ 75%
			// ^ value 50%, display 25%
			// & value 75%, display 50%
			const c = t[i];

			if (c === "@")
				targets.push(<span class={ ["target", "target-25", this.target] } data-pos={ t[++i] } />);
			else if (c === "#")
				targets.push(<span class={ ["target", "target-50", this.target] } data-pos={ t[++i] } />);
			else if (c === "$")
				targets.push(<span class={ ["target", "target-75", this.target] } data-pos={ t[++i] } />);

			// else if (c === "^")
			// 	targets.push(<span class={ ["target", "target-25", this.target] } data-pos={ t[++i] } />);
			// else if (c === "&")
			// 	targets.push(<span class={ ["target", "target-50", this.target] } data-pos={ t[++i] } />);

			else
				targets.push(<span class={ ["target", this.target] } data-pos={ c } />);
		}

		return <div class="skill-bound" data-passive={ this.passive ? 1 : 0 }>
			<div class="skill-range">
				{ this.rangeBack }
				{ this.rangeCells }
				{
					this.rangeBonus && this.Range > 0
						? <div class="skill-range-circle bonused">{ this.Range + 1 }</div>
						: <div class="skill-range-circle">{ this.Range }</div>
				}
			</div>

			<div class="skill-ap">
				<div>AP</div> { this.AP }
			</div>

			<div class="skill-grid">
				{ this.gridBack }
				{ this.IsGlobal ? "" : <span class="offset" data-pos={ offset } /> }
				{ targets }
			</div>

			{ this.IsGlobal ? <div class="global-text">고정 범위</div> : "" }
			{ this.target === "team" ? <div class="team-text">{ this.Skill.grid === "self" ? "본인 대상" : "아군 대상" }</div> : "" }
		</div>;
	}
}
</script>

<style lang="scss">
.skill-bound {
	$w: 14px;
	$h: ($w / 38) * 34;

	$highlited: #00efef;

	display: inline-block;
	width: 120px;
	text-shadow: 0 0 3px #000, 0 0 2px #000, 0 0 2px #000;

	&.skill-text {
		height: 60px;
	}

	span {
		position: absolute;
		width: $w;
		height: $h;

		background-image: url($assetsRoot + "skill-parallelogram.png");
		background-repeat: no-repeat;
		background-size: ($w * 10) $h;

		&.offset {
			background-position-x: -$w;
			z-index: 2;
		}
		&.target,
		&.target-50,
		&.target-25 {
			margin-top: -2px;
			margin-left: -2px;
			z-index: 2;
		}
		&.target {
			background-position-x: -($w * 2);
		}
		&.target-75 {
			background-position-x: -($w * 3);
		}
		&.target-50 {
			background-position-x: -($w * 4);
		}
		&.target-25 {
			background-position-x: -($w * 5);
		}
		&.range {
			background-position-x: -($w * 6);
		}
		/*
		&.target.team {
			background-position-x: -($w * 6);
		}
		&.target-75.team,
		&.target-50.team {
			background-position-x: -($w * 7);
		}
		&.target-25.team {
			background-position-x: -($w * 8);
		}
		*/
	}

	.skill-range {
		position: relative;
		margin-bottom: 5px;
		height: 24px;

		> span {
			top: 6px;
			@for $i from 0 to 6 {
				&[data-pos="#{$i + 1}"] {
					left: (2px + (($w + 1) * $i));
				}
			}
			&.range {
				margin-left: -2px;
				margin-top: -2px;
			}
		}

		> .skill-range-circle {
			float: right;
			width: 24px;
			height: 24px;
			background-image: url($assetsRoot + "range-circle.png");
			background-repeat: no-repeat;
			background-size: 24px 24px;
			line-height: 22px;
			text-align: center;
			font-size: 13px;
			color: #ffd91c;

			&.bonused {
				color: $highlited;
			}
		}
	}

	.skill-ap {
		float: right;
		margin: 2px 10px 0 0;
		line-height: 125%;
		font-weight: bold;
		font-size: 16px;
		color: $highlited;

		> div {
			color: #fff;
		}
	}

	&[data-passive="1"] {
		.skill-range,
		.skill-ap {
			opacity: 0.375;
		}
	}

	.skill-grid {
		position: relative;
		margin: 0 10px;
		width: 52px;
		height: 46px;

		> span {
			$x1: 0px;
			$x2: $w + 2;
			$x3: $x2 * 2;
			$x: $x1 $x2 $x3;

			$y3: 0px;
			$y2: $h + 3;
			$y1: $y2 * 2;
			$y: $y1 $y2 $y3;

			@for $i from 0 to 9 {
				&[data-pos="#{$i + 1}"] {
					top: (2px + nth($y, floor($i / 3) + 1));
					left: (2px + nth($x, ($i % 3) + 1) + floor($i / 3) * 2);
				}
			}
		}
	}

	.global-text {
		float: left;
		padding-left: 10px;
		font-size: 11px;
		text-align: left;
		color: $highlited;
	}
	.team-text {
		float: left;
		padding-left: 76px;
		font-size: 11px;
		text-align: left;
		color: $highlited;
	}
	.global-text + .team-text {
		padding-left: 24px;
	}
}
</style>
