// src/components/unit-face/index.tsx
import { AssetsRoot, ImageExtension } from "@/libs/Const";
import { FunctionalComponent, h } from "preact";

import style from "./style.scss";

interface UnitFaceProps {
	class?: string;
	uid: string;
	skin?: number;
	size?: number | string;
	type?: "mini";
	sd?: boolean;
}

export function GetUnitFaceURL (uid: string, skin: number = 0, sd: boolean = false): string {
	const ext = ImageExtension();
	if (!uid) return `${AssetsRoot}/${ext}/face/transparent.${ext}`;

	if (uid.startsWith("Core_") || uid.startsWith("Module_"))
		return `${AssetsRoot}/${ext}/face/${uid}_0.${ext}`;

	if (sd) {
		if (uid.startsWith("TbarIcon_"))
			return `${AssetsRoot}/${ext}/tbar/${uid}.${ext}`;

		if (skin === 20)
			return `${AssetsRoot}/${ext}/tbar/TbarIcon_${uid}_PS1.${ext}`;
		else if (skin === 21)
			return `${AssetsRoot}/${ext}/tbar/TbarIcon_${uid}_SS1.${ext}`;
		else if (skin > 0)
			return `${AssetsRoot}/${ext}/tbar/TbarIcon_${uid}_NS${skin}.${ext}`;

		return `${AssetsRoot}/${ext}/tbar/TbarIcon_${uid}_N.${ext}`;
	}

	return `${AssetsRoot}/${ext}/face/${uid}_${skin}.${ext}`;
}

const UnitFace: FunctionalComponent<UnitFaceProps> = (props) => {
	const path = GetUnitFaceURL(props.uid, props.skin || 0, props.sd || false);
	if (props.size) {
		return <img
			class={ `unit-face ${props.class || ""} ${style["unit-face"]}` }
			data-type={ props.type }
			src={ path }
			width={ props.size }
			height={ props.size }
		/>;
	}
	return <img class={ `unit-face ${props.class || ""} ${style["unit-face"]}` }
		data-type={ props.type }
		src={ path }
	/>;
};
export default UnitFace;

// src/components/UnitFace.vue
<script lang="tsx">
import Vue from "vue";
import Component from "vue-class-component";
import { Prop } from "vue-property-decorator";

import { AssetsRoot, ImageExtension } from "@/libs/Const";

@Component({})
export default class UnitFace extends Vue {
	@Prop({
		type: String,
		required: true,
	})
	private uid!: string;

	@Prop({
		type: Number,
		default: 0,
	})
	private skin!: number;

	@Prop({
		type: [Number, String],
		default: undefined,
	})
	private size!: number | string | undefined;

	@Prop({
		type: String,
		default: "",
	})
	private type!: string;

	public static GetURL (uid: string, skin: number = 0): string {
		const ext = ImageExtension();
		if (!uid) return `${AssetsRoot}/${ext}/face/transparent.${ext}`;

		if (uid.startsWith("Core_") || uid.startsWith("Module_"))
			return `${AssetsRoot}/${ext}/face/${uid}_0.${ext}`;

		return `${AssetsRoot}/${ext}/face/${uid}_${skin}.${ext}`;
	}

	private render () {
		const path = UnitFace.GetURL(this.uid, this.skin);
		if (this.size)
			return <img class="unit-face" data-type={ this.type } src={ path } width={ this.size } height={ this.size } />;
		else
			return <img class="unit-face" data-type={ this.type } src={ path } />;
	}
}
</script>

<style lang="scss">
.unit-face {
	&[data-type="mini"] {
		margin-right: 5px;
		border-radius: 4px;
		vertical-align: top;
	}
}
</style>
