// src/components/UnitBadge.vue
<script lang="tsx">
import Vue from "vue";
import Component from "vue-class-component";
import { Prop } from "vue-property-decorator";

import { ACTOR_CLASS, ROLE_TYPE } from "@/libs/Types/Enums";
import { LocaleGet } from "@/libs/Locale";

const typeName: Record<ACTOR_CLASS, string> = {
	[ACTOR_CLASS.LIGHT]: "LIGHT",
	[ACTOR_CLASS.AIR]: "MOBILITY",
	[ACTOR_CLASS.HEAVY]: "HEAVY",
};
const roleName: Record<ROLE_TYPE, string> = {
	[ROLE_TYPE.ATTACKER]: "ATTACKER",
	[ROLE_TYPE.DEFENDER]: "DEFENDER",
	[ROLE_TYPE.SUPPORTER]: "SUPPORTER",
};
const typeList = [
	"light",
	"air",
	"heavy",
];

@Component({})
export default class UnitBadge extends Vue {
	@Prop({
		type: Number,
		default: -1,
	})
	private type!: ACTOR_CLASS | -1;

	@Prop({
		type: Number,
		default: -1,
	})
	private role!: ROLE_TYPE | -1;

	@Prop({
		type: String,
		default: "",
	})
	private limit!: string;

	@Prop({
		type: Boolean,
		default: false,
	})
	private transparent!: boolean;

	@Prop({
		type: Boolean,
		default: false,
	})
	private black!: boolean;

	@Prop({
		type: String,
		default: "normal",
	})
	private size!: string;

	private get Limit () {
		return this.limit.toLowerCase();
	}

	private get Type (): ACTOR_CLASS {
		const table: Record<string, ACTOR_CLASS> = {
			light: ACTOR_CLASS.LIGHT,
			air: ACTOR_CLASS.AIR,
			heavy: ACTOR_CLASS.HEAVY,
		};
		if (this.Limit) {
			if (this.Limit.includes("+"))
				return table[this.Limit.split("+")[0]];
			else if (typeList.includes(this.Limit))
				return table[this.Limit];
			else
				return -1;
		}
		return this.type;
	}

	private get Role (): ROLE_TYPE {
		const table: Record<string, ROLE_TYPE> = {
			attacker: ROLE_TYPE.ATTACKER,
			defender: ROLE_TYPE.DEFENDER,
			supporter: ROLE_TYPE.SUPPORTER,
		};
		if (this.Limit) {
			if (this.Limit.includes("+"))
				return table[this.Limit.split("+")[1]];
			else if (!typeList.includes(this.Limit))
				return table[this.Limit];
			else
				return -1;
		}
		return this.role;
	}

	private get TypeName () {
		return typeName[this.Type] || "???";
	}

	private get RoleName () {
		return roleName[this.Role] || "???";
	}

	private render () {
		return <b-badge
			class="unit-badge"
			variant={ !this.transparent ? "primary" : "transparent" }
			data-size={ this.size }
			data-type={ this.Type }
			data-role={ this.Role }
			data-black={ this.black ? "1" : "0" }
		>
			<i />
			{
				this.Type !== -1 && this.Role !== -1
					? `${LocaleGet("COMMON_UNIT_TYPE_SHORT_" + this.TypeName)} ${LocaleGet("COMMON_UNIT_ROLE_" + this.RoleName)}`
					: this.Type !== -1
						? LocaleGet("COMMON_UNIT_TYPE_" + this.TypeName)
						: LocaleGet("COMMON_UNIT_ROLE_" + this.RoleName)
			}
		</b-badge>;
	}
}
</script>

<style lang="scss">
@mixin Build($basis: 14px) {
	$size: $basis;
	$w: $size;
	$h: $size;

	> i {
		width: $w;
		height: $h;
		background-size: ($w * 3) ($h * 2);
	}

	&[data-black="1"] {
		color: #000;

		> i {
			background-position-y: -$h;
		}
	}

	&[data-type="0"] > i {
		background-position-x: 0;
	}
	&[data-type="1"] > i {
		background-position-x: -($w * 2);
	}
	&[data-type="2"] > i {
		background-position-x: -$w;
	}

	&[data-type="-1"] {
		&[data-role="0"] > i {
			background-position-x: -$w;
		}
		&[data-role="1"] > i {
			background-position-x: 0;
		}
		&[data-role="2"] > i {
			background-position-x: -($w * 2);
		}
	}
}

.badge.unit-badge {
	margin-right: 4px;

	&:last-child {
		margin-right: 0;
	}

	> i {
		display: inline-block;
		margin: 0 3px 0 0;
		background-image: url($assetsRoot + "unit-type.png");
		background-position: 0 0;
		background-repeat: no-repeat;
		vertical-align: bottom;
	}
	&[data-type="-1"] {
		> i {
			background-image: url($assetsRoot + "unit-role.png");
		}

		&[data-role="-1"] > i {
			display: none;
		}
	}

	@include Build();

	&[data-size="large"] {
		@include Build(18px);
		font-size: 18px;
	}
}
</style>

// src/components/unit-badge/index.tsx
import { FunctionalComponent } from "preact";

import { ACTOR_CLASS, ROLE_TYPE } from "@/types/Enums";

import Locale from "@/components/locale";

import style from "./style.scss";

const typeName: Record<ACTOR_CLASS, string> = {
	[ACTOR_CLASS.LIGHT]: "LIGHT",
	[ACTOR_CLASS.AIR]: "MOBILITY",
	[ACTOR_CLASS.HEAVY]: "HEAVY",
};
const roleName: Record<ROLE_TYPE, string> = {
	[ROLE_TYPE.ATTACKER]: "ATTACKER",
	[ROLE_TYPE.DEFENDER]: "DEFENDER",
	[ROLE_TYPE.SUPPORTER]: "SUPPORTER",
};
const typeList = [
	"light",
	"air",
	"heavy",
];

interface UnitBadgeProps {
	class?: string;

	type?: ACTOR_CLASS;
	role?: ROLE_TYPE;
	limit?: string;
	transparent?: boolean;
	black?: boolean;
	size?: "normal" | "large";
}

const UnitBadge: FunctionalComponent<UnitBadgeProps> = (props) => {
	const limit = (props.limit || "").toLowerCase();
	const type = ((): ACTOR_CLASS | -1 => {
		const table: Record<string, ACTOR_CLASS> = {
			light: ACTOR_CLASS.LIGHT,
			air: ACTOR_CLASS.AIR,
			heavy: ACTOR_CLASS.HEAVY,
		};
		if (limit) {
			if (limit.includes("+"))
				return table[limit.split("+")[0]];
			else if (typeList.includes(limit))
				return table[limit];
			return -1;
		}
		const type = props.type;
		return type === undefined ? -1 : type;
	})();
	const role = ((): ROLE_TYPE | -1 => {
		const table: Record<string, ROLE_TYPE> = {
			attacker: ROLE_TYPE.ATTACKER,
			defender: ROLE_TYPE.DEFENDER,
			supporter: ROLE_TYPE.SUPPORTER,
		};
		if (limit) {
			if (limit.includes("+"))
				return table[limit.split("+")[1]];
			else if (!typeList.includes(limit))
				return table[limit];
			return -1;
		}
		const role = props.role;
		return role === undefined ? -1 : role;
	})();

	const TypeName = typeName[type] || "???";
	const RoleName = roleName[role] || "???";

	return <span class={ `badge unit-badge bg-${props.transparent ? "transparent" : "primary"} ${style["unit-badge"]} ${props.class || ""}` }
		data-size={ props.size || "normal" }
		data-type={ type }
		data-role={ role }
		data-black={ props.black }
	>
		<i />
		{ type !== -1 && role !== -1
			? [
				<Locale k={ `COMMON_UNIT_TYPE_SHORT_${TypeName}` } />,
				<Locale k={ `COMMON_UNIT_ROLE_${RoleName}` } />,
			].gap(" ")
			: type !== -1
				? <Locale k={ `COMMON_UNIT_TYPE_${TypeName}` } />
				: <Locale k={ `COMMON_UNIT_ROLE_${RoleName}` } />
		}
	</span>;
};
export default UnitBadge;
